In [1]:
import datetime as dt

In [2]:
today = dt.datetime.now()

In [5]:
today - dt.timedelta(days=5*365)

datetime.datetime(2016, 3, 6, 15, 20, 29, 527361)

In [4]:
today.month

3

In [3]:
import math

In [5]:
Q = math.ceil(today.month/3.)

In [6]:
Q

1

In [8]:
quarter = lambda x: math.ceil(x/3.)
for i in range(1, 13):
    print(i, quarter(i))

1 1
2 1
3 1
4 2
5 2
6 2
7 3
8 3
9 3
10 4
11 4
12 4

In [ ]:
import bs4 as bs
import requests
import pandas as pd
import re

company = 'Facebook Inc'
filing = '10-Q'
year = 2020
quarter = 'QTR3'
#get name of all filings 
download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
download = download.decode("utf-8").split('\n')

In [9]:
today.year

2021

In [56]:
import requests
import datetime as dt
import math
import pandas as pd
today = dt.datetime.now()
year = today.year
quarter = "QTR" + str(math.ceil(today.month/3.))
download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
download = download.decode("utf-8").split("\n")
download[11]

'1000045|NICHOLAS FINANCIAL INC|10-Q|2021-02-11|edgar/data/1000045/0001564590-21-005399.txt'

In [60]:
for i in download[9:15]:
    print(i)

CIK|Company Name|Form Type|Date Filed|Filename
--------------------------------------------------------------------------------
1000045|NICHOLAS FINANCIAL INC|10-Q|2021-02-11|edgar/data/1000045/0001564590-21-005399.txt
1000045|NICHOLAS FINANCIAL INC|4/A|2021-02-12|edgar/data/1000045/0001398344-21-003309.txt
1000045|NICHOLAS FINANCIAL INC|4|2021-02-08|edgar/data/1000045/0001496701-21-000001.txt
1000045|NICHOLAS FINANCIAL INC|4|2021-02-09|edgar/data/1000045/0001398344-21-002769.txt

In [73]:
for i in download[-9:-1]:
    print(i)

9984|BARNES GROUP INC|8-K|2021-02-12|edgar/data/9984/0000009984-21-000010.txt
9984|BARNES GROUP INC|8-K|2021-02-19|edgar/data/9984/0000009984-21-000059.txt
9984|BARNES GROUP INC|SC 13G/A|2021-01-26|edgar/data/9984/0000834237-21-001356.txt
9984|BARNES GROUP INC|SC 13G/A|2021-02-08|edgar/data/9984/0001567619-21-002446.txt
9984|BARNES GROUP INC|SC 13G/A|2021-02-10|edgar/data/9984/0001104659-21-017557.txt
9984|BARNES GROUP INC|SC 13G/A|2021-02-11|edgar/data/9984/0000814133-21-000026.txt
9984|BARNES GROUP INC|SC 13G/A|2021-02-12|edgar/data/9984/0000354204-21-000292.txt
9984|BARNES GROUP INC|SC 13G|2021-02-12|edgar/data/9984/0001315478-21-000007.txt

In [20]:
for count, i in enumerate(download):
    if "NICHOLAS" in i:
        print(count)
        print(i.split("|")[0])
        break

11
1000045

In [24]:
import requests
import datetime as dt
import math
today = dt.datetime.now()
year = today.year
quarter = "QTR" + str(math.ceil(today.month/3.))
download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
download = download.decode("utf-8").split("\n")
for i in download:
    if "NICHOLAS FINANCIAL INC" in i:
        print(i.split("|")[0])
        break

1000045

In [28]:
import requests
import datetime as dt
import math
today = dt.datetime.now()
year = today.year
quarter = "QTR" + str(math.ceil(today.month/3.))
download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
download = download.decode("utf-8").split("\n")
for count, i in enumerate(download):
    if "Apple Inc." in i:
        print(i.split("|")[0])
        print(count)
        break

320193
216394

In [35]:
import requests
import datetime as dt
import math
company = "Apple Inc."
today = dt.datetime.now()
year = today.year
month = today.month
for i in [month, month-1]:
    #print(i)
    quarter = "QTR" + str(math.ceil(i/3.))
    download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
    download = download.decode("utf-8").split("\n")
    for line in download:
        if company in line:
            cik = line.split("|")[0]
            print(cik)
            break

320193
320193

In [47]:
%%timeit
company = "Apple Inc."
def company_cik(company):
    today = dt.datetime.now()
    year = today.year
    month = today.month
    for i in [month, month-1]:
        quarter = "QTR" + str(math.ceil(i/3.))
        download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
        download = download.decode("utf-8").split("\n")
        for line in download:
            if company in line:
                cik = line.split("|")[0]
                return cik
print(company_cik(company))

320193
320193
320193
320193
320193
320193
320193
320193
947 ms ± 11.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [2]:
company = "Apple Inc."
def company_cik(company):
    today = dt.datetime.now()
    year = today.year
    month = today.month
    for i in [month, month-1]:
        quarter = "QTR" + str(math.ceil(i/3.))
        download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
        download = download.decode("utf-8").split("\n")
        for line in download:
            if company in line:
                print(line)
                return(line.split("|")[0])
print(company_cik(company))

320193|Apple Inc.|10-Q|2021-01-28|edgar/data/320193/0000320193-21-000010.txt
320193

In [40]:
company = "Apple Inc."
def link(company):
    today = dt.datetime.now()
    year = today.year
    month = today.month
    #is_qualified = lambda name, document: all([name==company, "10" in document])
    for i in [month, month-1]:
        #print(i)
        quarter = "QTR" + str(math.ceil(i/3.))
        download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
        download = download.decode("utf-8").split("\n")
        for line in download[11:-1]:
            #print(line.split("|")[1], line.split("|")[2])
            if company in line.split("|")[1]:
                #print(company, line.split("|")[0], line.split("|")[2])
                if "10-" in line.split("|")[2]:
                    return "https://www.sec.gov/Archives/" + line.split("|")[4]
print(link(company))

https://www.sec.gov/Archives/edgar/data/320193/0000320193-21-000010.txt

In [34]:
content = requests.get(filing_summary(filing_url(company))).content
soup = BeautifulSoup(content, 'lxml')
reports = soup.find('myreports')

for x, i in enumerate(reports):
    print(x, i)

0

1 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R1.htm</htmlfilename>
<longname>0001001 - Document - Cover Page</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CoverPage</role>
<shortname>Cover Page</shortname>
<menucategory>Cover</menucategory>
<position>1</position>
</report>
2

3 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R2.htm</htmlfilename>
<longname>1001002 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFOPERATIONSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>2</position>
</report>
4

5 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R3.htm</htmlfilename>
<longname>1002003 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOMEUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>3</position>
</report>
6

7 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R4.htm</htmlfilename>
<longname>1003004 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDBALANCESHEETSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>4</position>
</report>
8

9 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R5.htm</htmlfilename>
<longname>1004005 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited) (Parenthetical)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDBALANCESHEETSUnauditedParenthetical</role>
<shortname>CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited) (Parenthetical)</shortname>
<menucategory>Statements</menucategory>
<position>5</position>
</report>
10

11 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R6.htm</htmlfilename>
<longname>1005006 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITYUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>6</position>
</report>
12

13 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R7.htm</htmlfilename>
<longname>1006007 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFCASHFLOWSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>7</position>
</report>
14

15 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R8.htm</htmlfilename>
<longname>2101101 - Disclosure - Summary of Significant Accounting Policies</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</role>
<shortname>Summary of Significant Accounting Policies</shortname>
<menucategory>Notes</menucategory>
<position>8</position>
</report>
16

17 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R9.htm</htmlfilename>
<longname>2106102 - Disclosure - Revenue Recognition</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognition</role>
<shortname>Revenue Recognition</shortname>
<menucategory>Notes</menucategory>
<position>9</position>
</report>
18

19 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R10.htm</htmlfilename>
<longname>2111103 - Disclosure - Financial Instruments</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstruments</role>
<shortname>Financial Instruments</shortname>
<menucategory>Notes</menucategory>
<position>10</position>
</report>
20

21 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R11.htm</htmlfilename>
<longname>2120104 - Disclosure - Condensed Consolidated Financial Statement Details</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetails</role>
<shortname>Condensed Consolidated Financial Statement Details</shortname>
<menucategory>Notes</menucategory>
<position>11</position>
</report>
22

23 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R12.htm</htmlfilename>
<longname>2125105 - Disclosure - Income Taxes</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/IncomeTaxes</role>
<shortname>Income Taxes</shortname>
<menucategory>Notes</menucategory>
<position>12</position>
</report>
24

25 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R13.htm</htmlfilename>
<longname>2127106 - Disclosure - Debt</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/Debt</role>
<shortname>Debt</shortname>
<menucategory>Notes</menucategory>
<position>13</position>
</report>
26

27 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R14.htm</htmlfilename>
<longname>2132107 - Disclosure - Shareholders' Equity</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ShareholdersEquity</role>
<shortname>Shareholders' Equity</shortname>
<menucategory>Notes</menucategory>
<position>14</position>
</report>
28

29 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R15.htm</htmlfilename>
<longname>2134108 - Disclosure - Comprehensive Income</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ComprehensiveIncome</role>
<shortname>Comprehensive Income</shortname>
<menucategory>Notes</menucategory>
<position>15</position>
</report>
30

31 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R16.htm</htmlfilename>
<longname>2138109 - Disclosure - Benefit Plans</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/BenefitPlans</role>
<shortname>Benefit Plans</shortname>
<menucategory>Notes</menucategory>
<position>16</position>
</report>
32

33 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R17.htm</htmlfilename>
<longname>2143110 - Disclosure - Commitments and Contingencies</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CommitmentsandContingencies</role>
<shortname>Commitments and Contingencies</shortname>
<menucategory>Notes</menucategory>
<position>17</position>
</report>
34

35 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R18.htm</htmlfilename>
<longname>2147111 - Disclosure - Segment Information and Geographic Data</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SegmentInformationandGeographicData</role>
<shortname>Segment Information and Geographic Data</shortname>
<menucategory>Notes</menucategory>
<position>18</position>
</report>
36

37 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R19.htm</htmlfilename>
<longname>2202201 - Disclosure - Summary of Significant Accounting Policies (Policies)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesPolicies</role>
<shortname>Summary of Significant Accounting Policies (Policies)</shortname>
<menucategory>Policies</menucategory>
<parentrole>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</parentrole>
<position>19</position>
</report>
38

39 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R20.htm</htmlfilename>
<longname>2303301 - Disclosure - Summary of Significant Accounting Policies (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesTables</role>
<shortname>Summary of Significant Accounting Policies (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</parentrole>
<position>20</position>
</report>
40

41 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R21.htm</htmlfilename>
<longname>2307302 - Disclosure - Revenue Recognition (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionTables</role>
<shortname>Revenue Recognition (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/RevenueRecognition</parentrole>
<position>21</position>
</report>
42

43 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R22.htm</htmlfilename>
<longname>2312303 - Disclosure - Financial Instruments (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsTables</role>
<shortname>Financial Instruments (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/FinancialInstruments</parentrole>
<position>22</position>
</report>
44

45 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R23.htm</htmlfilename>
<longname>2321304 - Disclosure - Condensed Consolidated Financial Statement Details (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetailsTables</role>
<shortname>Condensed Consolidated Financial Statement Details (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetails</parentrole>
<position>23</position>
</report>
46

47 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R24.htm</htmlfilename>
<longname>2328305 - Disclosure - Debt (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/DebtTables</role>
<shortname>Debt (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/Debt</parentrole>
<position>24</position>
</report>
48

49 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R25.htm</htmlfilename>
<longname>2335306 - Disclosure - Comprehensive Income (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ComprehensiveIncomeTables</role>
<shortname>Comprehensive Income (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/ComprehensiveIncome</parentrole>
<position>25</position>
</report>
50

51 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R26.htm</htmlfilename>
<longname>2339307 - Disclosure - Benefit Plans (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/BenefitPlansTables</role>
<shortname>Benefit Plans (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/BenefitPlans</parentrole>
<position>26</position>
</report>
52

53 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R27.htm</htmlfilename>
<longname>2344308 - Disclosure - Commitments and Contingencies (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CommitmentsandContingenciesTables</role>
<shortname>Commitments and Contingencies (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/CommitmentsandContingencies</parentrole>
<position>27</position>
</report>
54

55 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R28.htm</htmlfilename>
<longname>2348309 - Disclosure - Segment Information and Geographic Data (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SegmentInformationandGeographicDataTables</role>
<shortname>Segment Information and Geographic Data (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/SegmentInformationandGeographicData</parentrole>
<position>28</position>
</report>
56

57 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R29.htm</htmlfilename>
<longname>2404401 - Disclosure - Summary of Significant Accounting Policies - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesAdditionalInformationDetails</role>
<shortname>Summary of Significant Accounting Policies - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>29</position>
</report>
58

59 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R30.htm</htmlfilename>
<longname>2405402 - Disclosure - Summary of Significant Accounting Policies - Computation of Basic and Diluted Earnings Per Share (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesComputationofBasicandDilutedEarningsPerShareDetails</role>
<shortname>Summary of Significant Accounting Policies - Computation of Basic and Diluted Earnings Per Share (Details)</shortname>
<menucategory>Details</menucategory>
<position>30</position>
</report>
60

61 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R31.htm</htmlfilename>
<longname>2408403 - Disclosure - Revenue Recognition - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionAdditionalInformationDetails</role>
<shortname>Revenue Recognition - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>31</position>
</report>
62

63 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R32.htm</htmlfilename>
<longname>2409404 - Disclosure - Revenue Recognition - Deferred Revenue, Expected Timing of Realization (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionDeferredRevenueExpectedTimingofRealizationDetails</role>
<shortname>Revenue Recognition - Deferred Revenue, Expected Timing of Realization (Details)</shortname>
<menucategory>Details</menucategory>
<position>32</position>
</report>
64

65 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R33.htm</htmlfilename>
<longname>2410405 - Disclosure - Revenue Recognition - Net Sales Disaggregated by Significant Products and Services (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionNetSalesDisaggregatedbySignificantProductsandServicesDetails</role>
<shortname>Revenue Recognition - Net Sales Disaggregated by Significant Products and Services (Details)</shortname>
<menucategory>Details</menucategory>
<position>33</position>
</report>
66

67 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R34.htm</htmlfilename>
<longname>2413406 - Disclosure - Financial Instruments - Cash, Cash Equivalents and Marketable Securities (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesDetails</role>
<shortname>Financial Instruments - Cash, Cash Equivalents and Marketable Securities (Details)</shortname>
<menucategory>Details</menucategory>
<position>34</position>
</report>
68

69 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R35.htm</htmlfilename>
<longname>2414407 - Disclosure - Financial Instruments - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsAdditionalInformationDetails</role>
<shortname>Financial Instruments - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>35</position>
</report>
70

71 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R36.htm</htmlfilename>
<longname>2415408 - Disclosure - Financial Instruments - Restricted Cash (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsRestrictedCashDetails</role>
<shortname>Financial Instruments - Restricted Cash (Details)</shortname>
<menucategory>Details</menucategory>
<position>36</position>
</report>
72

73 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R37.htm</htmlfilename>
<longname>2416409 - Disclosure - Financial Instruments - Derivative Instruments at Gross Fair Value (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsDerivativeInstrumentsatGrossFairValueDetails</role>
<shortname>Financial Instruments - Derivative Instruments at Gross Fair Value (Details)</shortname>
<menucategory>Details</menucategory>
<position>37</position>
</report>
74

75 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R38.htm</htmlfilename>
<longname>2417410 - Disclosure - Financial Instruments - Pre-Tax Gains and Losses of Derivative and Non-Derivative Instruments Designated as Cash Flow and Net Investment Hedges (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsPreTaxGainsandLossesofDerivativeandNonDerivativeInstrumentsDesignatedasCashFlowandNetInvestmentHedgesDetails</role>
<shortname>Financial Instruments - Pre-Tax Gains and Losses of Derivative and Non-Derivative Instruments Designated as Cash Flow and Net Investment Hedges (Details)</shortname>
<menucategory>Details</menucategory>

In [36]:
for x, i in enumerate(reports.find_all('report')[:-1]):
    print(x, i)

0 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R1.htm</htmlfilename>
<longname>0001001 - Document - Cover Page</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CoverPage</role>
<shortname>Cover Page</shortname>
<menucategory>Cover</menucategory>
<position>1</position>
</report>
1 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R2.htm</htmlfilename>
<longname>1001002 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFOPERATIONSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>2</position>
</report>
2 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R3.htm</htmlfilename>
<longname>1002003 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOMEUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>3</position>
</report>
3 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R4.htm</htmlfilename>
<longname>1003004 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDBALANCESHEETSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>4</position>
</report>
4 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R5.htm</htmlfilename>
<longname>1004005 - Statement - CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited) (Parenthetical)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDBALANCESHEETSUnauditedParenthetical</role>
<shortname>CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited) (Parenthetical)</shortname>
<menucategory>Statements</menucategory>
<position>5</position>
</report>
5 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R6.htm</htmlfilename>
<longname>1005006 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITYUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>6</position>
</report>
6 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R7.htm</htmlfilename>
<longname>1006007 - Statement - CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CONDENSEDCONSOLIDATEDSTATEMENTSOFCASHFLOWSUnaudited</role>
<shortname>CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)</shortname>
<menucategory>Statements</menucategory>
<position>7</position>
</report>
7 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R8.htm</htmlfilename>
<longname>2101101 - Disclosure - Summary of Significant Accounting Policies</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</role>
<shortname>Summary of Significant Accounting Policies</shortname>
<menucategory>Notes</menucategory>
<position>8</position>
</report>
8 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R9.htm</htmlfilename>
<longname>2106102 - Disclosure - Revenue Recognition</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognition</role>
<shortname>Revenue Recognition</shortname>
<menucategory>Notes</menucategory>
<position>9</position>
</report>
9 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R10.htm</htmlfilename>
<longname>2111103 - Disclosure - Financial Instruments</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstruments</role>
<shortname>Financial Instruments</shortname>
<menucategory>Notes</menucategory>
<position>10</position>
</report>
10 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R11.htm</htmlfilename>
<longname>2120104 - Disclosure - Condensed Consolidated Financial Statement Details</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetails</role>
<shortname>Condensed Consolidated Financial Statement Details</shortname>
<menucategory>Notes</menucategory>
<position>11</position>
</report>
11 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R12.htm</htmlfilename>
<longname>2125105 - Disclosure - Income Taxes</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/IncomeTaxes</role>
<shortname>Income Taxes</shortname>
<menucategory>Notes</menucategory>
<position>12</position>
</report>
12 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R13.htm</htmlfilename>
<longname>2127106 - Disclosure - Debt</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/Debt</role>
<shortname>Debt</shortname>
<menucategory>Notes</menucategory>
<position>13</position>
</report>
13 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R14.htm</htmlfilename>
<longname>2132107 - Disclosure - Shareholders' Equity</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ShareholdersEquity</role>
<shortname>Shareholders' Equity</shortname>
<menucategory>Notes</menucategory>
<position>14</position>
</report>
14 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R15.htm</htmlfilename>
<longname>2134108 - Disclosure - Comprehensive Income</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ComprehensiveIncome</role>
<shortname>Comprehensive Income</shortname>
<menucategory>Notes</menucategory>
<position>15</position>
</report>
15 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R16.htm</htmlfilename>
<longname>2138109 - Disclosure - Benefit Plans</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/BenefitPlans</role>
<shortname>Benefit Plans</shortname>
<menucategory>Notes</menucategory>
<position>16</position>
</report>
16 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R17.htm</htmlfilename>
<longname>2143110 - Disclosure - Commitments and Contingencies</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CommitmentsandContingencies</role>
<shortname>Commitments and Contingencies</shortname>
<menucategory>Notes</menucategory>
<position>17</position>
</report>
17 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R18.htm</htmlfilename>
<longname>2147111 - Disclosure - Segment Information and Geographic Data</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SegmentInformationandGeographicData</role>
<shortname>Segment Information and Geographic Data</shortname>
<menucategory>Notes</menucategory>
<position>18</position>
</report>
18 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R19.htm</htmlfilename>
<longname>2202201 - Disclosure - Summary of Significant Accounting Policies (Policies)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesPolicies</role>
<shortname>Summary of Significant Accounting Policies (Policies)</shortname>
<menucategory>Policies</menucategory>
<parentrole>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</parentrole>
<position>19</position>
</report>
19 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R20.htm</htmlfilename>
<longname>2303301 - Disclosure - Summary of Significant Accounting Policies (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesTables</role>
<shortname>Summary of Significant Accounting Policies (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/SummaryofSignificantAccountingPolicies</parentrole>
<position>20</position>
</report>
20 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R21.htm</htmlfilename>
<longname>2307302 - Disclosure - Revenue Recognition (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionTables</role>
<shortname>Revenue Recognition (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/RevenueRecognition</parentrole>
<position>21</position>
</report>
21 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R22.htm</htmlfilename>
<longname>2312303 - Disclosure - Financial Instruments (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsTables</role>
<shortname>Financial Instruments (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/FinancialInstruments</parentrole>
<position>22</position>
</report>
22 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R23.htm</htmlfilename>
<longname>2321304 - Disclosure - Condensed Consolidated Financial Statement Details (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetailsTables</role>
<shortname>Condensed Consolidated Financial Statement Details (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/CondensedConsolidatedFinancialStatementDetails</parentrole>
<position>23</position>
</report>
23 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R24.htm</htmlfilename>
<longname>2328305 - Disclosure - Debt (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/DebtTables</role>
<shortname>Debt (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/Debt</parentrole>
<position>24</position>
</report>
24 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R25.htm</htmlfilename>
<longname>2335306 - Disclosure - Comprehensive Income (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/ComprehensiveIncomeTables</role>
<shortname>Comprehensive Income (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/ComprehensiveIncome</parentrole>
<position>25</position>
</report>
25 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R26.htm</htmlfilename>
<longname>2339307 - Disclosure - Benefit Plans (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/BenefitPlansTables</role>
<shortname>Benefit Plans (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/BenefitPlans</parentrole>
<position>26</position>
</report>
26 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R27.htm</htmlfilename>
<longname>2344308 - Disclosure - Commitments and Contingencies (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/CommitmentsandContingenciesTables</role>
<shortname>Commitments and Contingencies (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/CommitmentsandContingencies</parentrole>
<position>27</position>
</report>
27 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R28.htm</htmlfilename>
<longname>2348309 - Disclosure - Segment Information and Geographic Data (Tables)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SegmentInformationandGeographicDataTables</role>
<shortname>Segment Information and Geographic Data (Tables)</shortname>
<menucategory>Tables</menucategory>
<parentrole>http://www.apple.com/role/SegmentInformationandGeographicData</parentrole>
<position>28</position>
</report>
28 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R29.htm</htmlfilename>
<longname>2404401 - Disclosure - Summary of Significant Accounting Policies - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesAdditionalInformationDetails</role>
<shortname>Summary of Significant Accounting Policies - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>29</position>
</report>
29 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R30.htm</htmlfilename>
<longname>2405402 - Disclosure - Summary of Significant Accounting Policies - Computation of Basic and Diluted Earnings Per Share (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/SummaryofSignificantAccountingPoliciesComputationofBasicandDilutedEarningsPerShareDetails</role>
<shortname>Summary of Significant Accounting Policies - Computation of Basic and Diluted Earnings Per Share (Details)</shortname>
<menucategory>Details</menucategory>
<position>30</position>
</report>
30 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R31.htm</htmlfilename>
<longname>2408403 - Disclosure - Revenue Recognition - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionAdditionalInformationDetails</role>
<shortname>Revenue Recognition - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>31</position>
</report>
31 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R32.htm</htmlfilename>
<longname>2409404 - Disclosure - Revenue Recognition - Deferred Revenue, Expected Timing of Realization (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionDeferredRevenueExpectedTimingofRealizationDetails</role>
<shortname>Revenue Recognition - Deferred Revenue, Expected Timing of Realization (Details)</shortname>
<menucategory>Details</menucategory>
<position>32</position>
</report>
32 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R33.htm</htmlfilename>
<longname>2410405 - Disclosure - Revenue Recognition - Net Sales Disaggregated by Significant Products and Services (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/RevenueRecognitionNetSalesDisaggregatedbySignificantProductsandServicesDetails</role>
<shortname>Revenue Recognition - Net Sales Disaggregated by Significant Products and Services (Details)</shortname>
<menucategory>Details</menucategory>
<position>33</position>
</report>
33 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R34.htm</htmlfilename>
<longname>2413406 - Disclosure - Financial Instruments - Cash, Cash Equivalents and Marketable Securities (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesDetails</role>
<shortname>Financial Instruments - Cash, Cash Equivalents and Marketable Securities (Details)</shortname>
<menucategory>Details</menucategory>
<position>34</position>
</report>
34 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R35.htm</htmlfilename>
<longname>2414407 - Disclosure - Financial Instruments - Additional Information (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsAdditionalInformationDetails</role>
<shortname>Financial Instruments - Additional Information (Details)</shortname>
<menucategory>Details</menucategory>
<position>35</position>
</report>
35 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R36.htm</htmlfilename>
<longname>2415408 - Disclosure - Financial Instruments - Restricted Cash (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsRestrictedCashDetails</role>
<shortname>Financial Instruments - Restricted Cash (Details)</shortname>
<menucategory>Details</menucategory>
<position>36</position>
</report>
36 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R37.htm</htmlfilename>
<longname>2416409 - Disclosure - Financial Instruments - Derivative Instruments at Gross Fair Value (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsDerivativeInstrumentsatGrossFairValueDetails</role>
<shortname>Financial Instruments - Derivative Instruments at Gross Fair Value (Details)</shortname>
<menucategory>Details</menucategory>
<position>37</position>
</report>
37 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>
<htmlfilename>R38.htm</htmlfilename>
<longname>2417410 - Disclosure - Financial Instruments - Pre-Tax Gains and Losses of Derivative and Non-Derivative Instruments Designated as Cash Flow and Net Investment Hedges (Details)</longname>
<reporttype>Sheet</reporttype>
<role>http://www.apple.com/role/FinancialInstrumentsPreTaxGainsandLossesofDerivativeandNonDerivativeInstrumentsDesignatedasCashFlowandNetInvestmentHedgesDetails</role>
<shortname>Financial Instruments - Pre-Tax Gains and Losses of Derivative and Non-Derivative Instruments Designated as Cash Flow and Net Investment Hedges (Details)</shortname>
<menucategory>Details</menucategory>
<position>38</position>
</report>
38 <report instance="aapl-20201226.htm">
<isdefault>false</isdefault>
<hasembeddedreports>false</hasembeddedreports>

In [38]:
for i in reports.find_all('report')[:-1]:
    print(i.shortname.text)

Cover Page
CONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)
CONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)
CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)
CONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited) (Parenthetical)
CONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY (Unaudited)
CONDENSED CONSOLIDATED STATEMENTS OF CASH FLOWS (Unaudited)
Summary of Significant Accounting Policies
Revenue Recognition
Financial Instruments
Condensed Consolidated Financial Statement Details
Income Taxes
Debt
Shareholders' Equity
Comprehensive Income
Benefit Plans
Commitments and Contingencies
Segment Information and Geographic Data
Summary of Significant Accounting Policies (Policies)
Summary of Significant Accounting Policies (Tables)
Revenue Recognition (Tables)
Financial Instruments (Tables)
Condensed Consolidated Financial Statement Details (Tables)
Debt (Tables)
Comprehensive Income (Tables)
Benefit Plans (Tables)
Commitments and Contingencies (Tables)
Segment Information and Geographic Data (Tables)
Summary of Significant Accounting Policies - Additional Information (Details)
Summary of Significant Accounting Policies - Computation of Basic and Diluted Earnings Per Share (Details)
Revenue Recognition - Additional Information (Details)
Revenue Recognition - Deferred Revenue, Expected Timing of Realization (Details)
Revenue Recognition - Net Sales Disaggregated by Significant Products and Services (Details)
Financial Instruments - Cash, Cash Equivalents and Marketable Securities (Details)
Financial Instruments - Additional Information (Details)
Financial Instruments - Restricted Cash (Details)
Financial Instruments - Derivative Instruments at Gross Fair Value (Details)
Financial Instruments - Pre-Tax Gains and Losses of Derivative and Non-Derivative Instruments Designated as Cash Flow and Net Investment Hedges (Details)
Financial Instruments - Derivative Instruments Designated as Fair Value Hedges and Related Hedged Items (Details)
Financial Instruments - Notional Amounts and Credit Risk Amounts Associated with Derivative Instruments (Details)
Condensed Consolidated Financial Statement Details - Property, Plant and Equipment, Net (Details)
Condensed Consolidated Financial Statement Details - Other Non-Current Liabilities (Details)
Condensed Consolidated Financial Statement Details - Other Income/(Expense), Net (Details)
Income Taxes - Additional Information (Details)
Debt - Additional Information (Details)
Debt - Summary of Cash Flows Associated with Commercial Paper (Details)
Debt - Summary of Term Debt (Details)
Shareholders' Equity - Additional Information (Details)
Comprehensive Income - Pre-tax Amounts Reclassified from AOCI into the Condensed Consolidated Statements of Operations (Details)
Comprehensive Income - Change in AOCI by Component (Details)
Benefit Plans - Additional Information (Details)
Benefit Plans - Restricted Stock Units Activity and Related Information (Details)
Benefit Plans - Summary of Share-Based Compensation Expense and the Related Income Tax Benefit (Details)
Commitments and Contingencies - Changes in Accrued Warranties and Related Costs (Details)
Commitments and Contingencies - Additional Information (Details)
Segment Information and Geographic Data - Summary Information by Reportable Segment (Details)
Segment Information and Geographic Data - Reconciliation of Segment Operating Income to the Condensed Consolidated Statements of Operations (Details)

In [2]:
#
import requests
import datetime as dt
import math
from bs4 import BeautifulSoup
import numpy as np
import re

ModuleNotFoundError: No module named 'bs4'

In [14]:
company = "Apple Inc."
def filing_url(company):
    today = dt.datetime.now()
    year = today.year
    month = today.month
    #is_qualified = lambda name, document: all([name==company, "10" in document])
    for i in [month, month-1]:
        #print(i)
        quarter = "QTR" + str(math.ceil(i/3.))
        download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
        download = download.decode("utf-8").split("\n")
        for line in download[11:-1]:
            #print(line.split("|")[1], line.split("|")[2])
            if company in line.split("|")[1]:
                #print(company, line.split("|")[0], line.split("|")[2])
                if "10-" in line.split("|")[2]:
                    return "https://www.sec.gov/Archives/" + line.split("|")[4].replace('-', '').replace('.txt', '')
print(filing_url(company))

https://www.sec.gov/Archives/edgar/data/320193/000032019321000010

In [18]:
#
company = "Apple Inc."
def filing_url(company):
    today = dt.datetime.now()
    for i in range(0,12,3):
        #print(i)
        now = today - dt.timedelta(days=i*30)
        #print(now)
        year = now.year
        quarter = "QTR" + str(math.ceil(now.month/3.))
        #print(quarter, year)
        download = requests.get(f'https://www.sec.gov/Archives/edgar/full-index/{year}/{quarter}/master.idx').content
        download = download.decode("utf-8").split("\n")
        for line in download[11:-1]:
            #print(line.split("|")[1], line.split("|")[2])
            if company in line.split("|")[1]:
                #print(company, line.split("|")[0], line.split("|")[2])
                if "10-K" in line.split("|")[2]:
                    return "https://www.sec.gov/Archives/" + line.split("|")[4].replace('-', '').replace('.txt', '')
print(filing_url(company))

https://www.sec.gov/Archives/edgar/data/320193/000032019320000096

In [19]:
#
def filing_summary(filing_url):
    return filing_url + '/FilingSummary.xml'
print(filing_summary(filing_url(company)))

https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/FilingSummary.xml

In [27]:
#
def statement_urls(filing_summary_url):
    content = requests.get(filing_summary(filing_url(company))).content
    soup = BeautifulSoup(content, 'lxml')
    reports = soup.find('myreports')
    
    # define the statements we want to look for
    item1 = r"CONSOLIDATED BALANCE SHEETS"
    item2 = r"CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME"
    item3 = r"CONSOLIDATED STATEMENTS OF CASH FLOWS"
    item4 = r"CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY"
    
    # store them in a list
    report_list = [item1, item2, item3, item4]
    
    #url_list = []
    url_dict = {}
    
    for i in reports.find_all('report')[:-1]:
#         print(i.shortname.text)
#         print(a + '/' + i.htmlfilename.text)
        if i.shortname.text.upper() in report_list:
            #url_list.append(a + '/' + i.htmlfilename.text)
            url_dict[i.shortname.text.upper()]=a + '/' + i.htmlfilename.text
            #print("A document found.")
    
    return url_dict

a = filing_url(company)
print(a)
b = filing_summary(a)
print(b)
urls = statement_urls(b)
for name, link in urls.items():
    print(name, link)

https://www.sec.gov/Archives/edgar/data/320193/000032019320000096
https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/FilingSummary.xml
CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/R3.htm
CONSOLIDATED BALANCE SHEETS https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/R4.htm
CONSOLIDATED STATEMENTS OF SHAREHOLDERS' EQUITY https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/R6.htm
CONSOLIDATED STATEMENTS OF CASH FLOWS https://www.sec.gov/Archives/edgar/data/320193/000032019320000096/R7.htm

In [1]:
import pandas as pd
import html5lib
from bs4 import BeautifulSoup

In [50]:
tables = pd.read_html("https://www.marketwatch.com/investing/stock/spg/financials/balance-sheet", match="Item", index_col=0)

In [51]:
len(tables)

2

In [52]:
tables[0]

,2016,2017,2018,2019,2020,5-year trend
Item Item,,,,,,
Cash & Short Term Investments Cash & Short Term Investments,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
Cash & Short Term Investments Growth Cash & Short Term Investments Growth,-,164.67%,-65.30%,30.14%,51.13%,NaN
Cash Only Cash Only,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
Total Short-Term Investments Total Short-Term Investments,-,-,-,-,-,NaN
Short-Term Receivables Short-Term Receivables,-,-,-,-,597.6M,NaN
Short Term Receivables Growth Short Term Receivables Growth,-,-,-,-,-,NaN
Investment Securities Investment Securities,-,-,-,-,-,NaN
Investment Securities Growth Investment Securities Growth,-,-,-,-,-,NaN
Securities in Custody Securities in Custody,-,-,-,-,-,NaN
Securities in Custody Growth Securities in Custody Growth,-,-,-,-,-,NaN
Other Investments Other Investments,366.73M,330.79M,293.83M,416.31M,391.67M,NaN
"Net Property, Plant & Equipments Net Property, Plant & Equipments",-,-,-,-,512.91M,NaN
Other Assets (Including Intangibles) Other Assets (Including Intangibles),26.01B,26.24B,25.89B,25.53B,1.24B,NaN
Other Assets Other Assets,25.73B,26.03B,25.74B,25.43B,1.19B,NaN
Intangible Assets Intangible Assets,285.14M,208.56M,150.74M,95.85M,55.06M,NaN
Total Assets Total Assets,31.1B,32.26B,30.69B,31.23B,34.79B,NaN
Total Assets Growth Total Assets Growth,-,3.71%,-4.87%,1.78%,11.38%,NaN
Return On Average Assets Return On Average Assets,-,-,-,-,3.72%,NaN

In [24]:
tables[0].index

Index(['Cash & Short Term Investments  Cash & Short Term Investments',
       'Cash & Short Term Investments Growth  Cash & Short Term Investments Growth',
       'Cash Only  Cash Only',
       'Total Short-Term Investments  Total Short-Term Investments',
       'Short-Term Receivables  Short-Term Receivables',
       'Short Term Receivables Growth  Short Term Receivables Growth',
       'Investment Securities  Investment Securities',
       'Investment Securities Growth  Investment Securities Growth',
       'Securities in Custody  Securities in Custody',
       'Securities in Custody Growth  Securities in Custody Growth',
       'Other Investments  Other Investments',
       'Net Property, Plant & Equipments  Net Property, Plant & Equipments',
       'Other Assets (Including Intangibles)  Other Assets (Including Intangibles)',
       'Other Assets  Other Assets', 'Intangible Assets  Intangible Assets',
       'Total Assets  Total Assets',
       'Total Assets Growth  Total Assets Growth',
       'Return On Average Assets  Return On Average Assets'],
      dtype='object', name='Item  Item')

In [25]:
tables[0].index[0]

'Cash & Short Term Investments  Cash & Short Term Investments'

In [27]:
tables[0].index[0].split()

['Cash',
 '&',
 'Short',
 'Term',
 'Investments',
 'Cash',
 '&',
 'Short',
 'Term',
 'Investments']

In [30]:
set(tables[0].index[0].split())

{'&', 'Cash', 'Investments', 'Short', 'Term'}

In [31]:
dict.fromkeys(tables[0].index[0].split())

{'Cash': None, '&': None, 'Short': None, 'Term': None, 'Investments': None}

In [44]:
" ".join(dict.fromkeys(tables[0].index[0].lower().split()))

'cash & short term investments'

In [45]:
%timeit list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[0].index))

132 µs ± 9.68 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [46]:
%timeit list(map(lambda x: " ".join(dict.fromkeys(x.split())), tables[0].index))

121 µs ± 6.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [55]:
%%timeit
new_index = []
for i in tables[0].index:
    new_index.append(" ".join(dict.fromkeys(i.lower().split())))

123 µs ± 8.64 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [37]:
tables[0].index

Index(['Cash & Short Term Investments  Cash & Short Term Investments',
       'Cash & Short Term Investments Growth  Cash & Short Term Investments Growth',
       'Cash Only  Cash Only',
       'Total Short-Term Investments  Total Short-Term Investments',
       'Short-Term Receivables  Short-Term Receivables',
       'Short Term Receivables Growth  Short Term Receivables Growth',
       'Investment Securities  Investment Securities',
       'Investment Securities Growth  Investment Securities Growth',
       'Securities in Custody  Securities in Custody',
       'Securities in Custody Growth  Securities in Custody Growth',
       'Other Investments  Other Investments',
       'Net Property, Plant & Equipments  Net Property, Plant & Equipments',
       'Other Assets (Including Intangibles)  Other Assets (Including Intangibles)',
       'Other Assets  Other Assets', 'Intangible Assets  Intangible Assets',
       'Total Assets  Total Assets',
       'Total Assets Growth  Total Assets Growth',
       'Return On Average Assets  Return On Average Assets'],
      dtype='object', name='Item  Item')

In [47]:
tables[0].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[0].index))

In [48]:
tables[0].index

Index(['cash & short term investments', 'cash & short term investments growth',
       'cash only', 'total short-term investments', 'short-term receivables',
       'short term receivables growth', 'investment securities',
       'investment securities growth', 'securities in custody',
       'securities in custody growth', 'other investments',
       'net property, plant & equipments',
       'other assets (including intangibles)', 'other assets',
       'intangible assets', 'total assets', 'total assets growth',
       'return on average assets'],
      dtype='object')

In [49]:
tables[0]

,2016,2017,2018,2019,2020,5-year trend
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%,NaN
cash only,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
total short-term investments,-,-,-,-,-,NaN
short-term receivables,-,-,-,-,597.6M,NaN
short term receivables growth,-,-,-,-,-,NaN
investment securities,-,-,-,-,-,NaN
investment securities growth,-,-,-,-,-,NaN
securities in custody,-,-,-,-,-,NaN
securities in custody growth,-,-,-,-,-,NaN
other investments,366.73M,330.79M,293.83M,416.31M,391.67M,NaN
"net property, plant & equipments",-,-,-,-,512.91M,NaN
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B,NaN
other assets,25.73B,26.03B,25.74B,25.43B,1.19B,NaN
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M,NaN
total assets,31.1B,32.26B,30.69B,31.23B,34.79B,NaN
total assets growth,-,3.71%,-4.87%,1.78%,11.38%,NaN
return on average assets,-,-,-,-,3.72%,NaN

In [71]:
%%timeit
tables = pd.read_html("https://www.marketwatch.com/investing/stock/spg/financials/balance-sheet", match="Item", index_col=0)
new_index = []
for x in range(len(tables)):
    new_index = []
    for y in range(len(tables[x].index)):
        new_index.append(" ".join(dict.fromkeys(tables[x].index[y].lower().split())))
    tables[x].index = new_index

700 ms ± 71.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [70]:
tables[0]

,2016,2017,2018,2019,2020,5-year trend
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%,NaN
cash only,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
total short-term investments,-,-,-,-,-,NaN
short-term receivables,-,-,-,-,597.6M,NaN
short term receivables growth,-,-,-,-,-,NaN
investment securities,-,-,-,-,-,NaN
investment securities growth,-,-,-,-,-,NaN
securities in custody,-,-,-,-,-,NaN
securities in custody growth,-,-,-,-,-,NaN
other investments,366.73M,330.79M,293.83M,416.31M,391.67M,NaN
"net property, plant & equipments",-,-,-,-,512.91M,NaN
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B,NaN
other assets,25.73B,26.03B,25.74B,25.43B,1.19B,NaN
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M,NaN
total assets,31.1B,32.26B,30.69B,31.23B,34.79B,NaN
total assets growth,-,3.71%,-4.87%,1.78%,11.38%,NaN
return on average assets,-,-,-,-,3.72%,NaN

In [35]:
%%timeit
tables = pd.read_html("https://www.marketwatch.com/investing/stock/spg/financials/balance-sheet", match="Item", index_col=0)
tables[0].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[0].index))
tables[1].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[1].index))

873 ms ± 450 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [19]:
tables[0]

,2016,2017,2018,2019,2020,5-year trend
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%,NaN
cash only,560.06M,1.48B,514.34M,669.37M,1.01B,NaN
total short-term investments,-,-,-,-,-,NaN
short-term receivables,-,-,-,-,597.6M,NaN
short term receivables growth,-,-,-,-,-,NaN
investment securities,-,-,-,-,-,NaN
investment securities growth,-,-,-,-,-,NaN
securities in custody,-,-,-,-,-,NaN
securities in custody growth,-,-,-,-,-,NaN
other investments,366.73M,330.79M,293.83M,416.31M,391.67M,NaN
"net property, plant & equipments",-,-,-,-,512.91M,NaN
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B,NaN
other assets,25.73B,26.03B,25.74B,25.43B,1.19B,NaN
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M,NaN
total assets,31.1B,32.26B,30.69B,31.23B,34.79B,NaN
total assets growth,-,3.71%,-4.87%,1.78%,11.38%,NaN
return on average assets,-,-,-,-,3.72%,NaN

In [74]:
tables[1]

,2016,2017,2018,2019,2020,5-year trend
total debt,22.98B,24.63B,23.31B,24.68B,27.24B,NaN
total debt growth,-,7.20%,-5.39%,5.90%,10.37%,NaN
st debt & current portion lt,2.23B,2.06B,1.42B,2.86B,2.36B,NaN
short term debt,-,-,-,-,32.79M,NaN
current portion of long term debt,2.23B,2.06B,1.42B,2.86B,2.32B,NaN
long-term debt,20.74B,22.57B,21.89B,21.82B,24.88B,NaN
lt debt excl. capitalized leases,20.74B,22.57B,21.89B,21.31B,24.4B,NaN
capitalized lease obligations,-,-,-,-,-,NaN
total debt / assets,73.87%,76.36%,75.95%,79.02%,78.30%,NaN
deferred taxes,-,-,-,-,-,NaN
other liabilities,3.03B,3.2B,3.35B,3.42B,3.89B,NaN
other liabilities (excl. deferred income),3.03B,3.2B,3.35B,3.42B,3.89B,NaN
total liabilities,26.01B,27.83B,26.66B,28.1B,31.13B,NaN
total liabilities growth,-,7.01%,-4.20%,5.41%,10.77%,NaN
preferred stock (carrying value),-,-,-,-,42.09M,NaN
redeemable preferred stock,43.41M,43.08M,42.75M,42.42M,42.09M,NaN
non-redeemable preferred stock,-,-,-,-,-,NaN
common equity (total),4.27B,3.64B,3.25B,2.48B,3B,NaN
common stock par/carry value,32K,32K,32K,32K,34K,NaN
additional paid-in capital/capital surplus,9.52B,9.61B,9.7B,9.76B,11.18B,NaN
retained earnings,(4.46B),(4.78B),(4.89B),(5.38B),(6.1B),NaN
esop debt guarantee,-,-,-,-,-,NaN
cumulative translation adjustment/unrealized for. exch. gain,(157.86M),(118.14M),(158.9M),-,-,NaN
unrealized gain/loss marketable securities,13.36M,(370K),(46K),-,-,NaN
revaluation reserves,-,-,-,-,-,NaN
other appropriated reserves,-,-,-,-,(188.68M),NaN
unappropriated reserves,-,-,-,-,-,NaN
treasury stock,(682.56M),(1.08B),(1.43B),(1.77B),(1.89B),NaN
common equity / total assets,13.72%,11.29%,10.60%,7.95%,8.62%,NaN
total shareholders' equity,4.27B,3.64B,3.25B,2.48B,3.04B,NaN
total shareholders' equity / assets,13.72%,11.29%,10.60%,7.95%,8.74%,NaN
return on average assets,-,-,-,-,3.72%,NaN
accumulated minority interest,787.23M,743.08M,730.44M,603.91M,618.77M,NaN
total equity,5.05B,4.39B,3.98B,3.09B,3.66B,NaN
liabilities & shareholders' equity,31.1B,32.26B,30.69B,31.23B,34.79B,NaN

In [8]:
tables[0].columns

Index(['2016', '2017', '2018', '2019', '2020', '5-year trend'], dtype='object')

In [11]:
tables[0].columns[-1]

'5-year trend'

In [12]:
tables[0].columns[-1].isdigit()

False

In [13]:
tables[0].columns[-2].isdigit()

True

In [16]:
tables[0].drop("5-year trend", axis="columns", inplace=True)

In [22]:
tables[0].drop(tables[0].columns[-1], axis="columns")

,2016,2017,2018,2019,2020
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%
cash only,560.06M,1.48B,514.34M,669.37M,1.01B
total short-term investments,-,-,-,-,-
short-term receivables,-,-,-,-,597.6M
short term receivables growth,-,-,-,-,-
investment securities,-,-,-,-,-
investment securities growth,-,-,-,-,-
securities in custody,-,-,-,-,-
securities in custody growth,-,-,-,-,-
other investments,366.73M,330.79M,293.83M,416.31M,391.67M
"net property, plant & equipments",-,-,-,-,512.91M
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B
other assets,25.73B,26.03B,25.74B,25.43B,1.19B
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M
total assets,31.1B,32.26B,30.69B,31.23B,34.79B
total assets growth,-,3.71%,-4.87%,1.78%,11.38%
return on average assets,-,-,-,-,3.72%

In [17]:
tables[0]

,2016,2017,2018,2019,2020
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%
cash only,560.06M,1.48B,514.34M,669.37M,1.01B
total short-term investments,-,-,-,-,-
short-term receivables,-,-,-,-,597.6M
short term receivables growth,-,-,-,-,-
investment securities,-,-,-,-,-
investment securities growth,-,-,-,-,-
securities in custody,-,-,-,-,-
securities in custody growth,-,-,-,-,-
other investments,366.73M,330.79M,293.83M,416.31M,391.67M
"net property, plant & equipments",-,-,-,-,512.91M
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B
other assets,25.73B,26.03B,25.74B,25.43B,1.19B
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M
total assets,31.1B,32.26B,30.69B,31.23B,34.79B
total assets growth,-,3.71%,-4.87%,1.78%,11.38%
return on average assets,-,-,-,-,3.72%

In [36]:
%%timeit
tables = pd.read_html("https://www.marketwatch.com/investing/stock/spg/financials/balance-sheet", match="Item", index_col=0)
for i in range(len(tables)):
    tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
    if not tables[i].columns[-1].isdigit():
        tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)

648 ms ± 161 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [37]:
tables[0]

,2016,2017,2018,2019,2020
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%
cash only,560.06M,1.48B,514.34M,669.37M,1.01B
total short-term investments,-,-,-,-,-
short-term receivables,-,-,-,-,597.6M
short term receivables growth,-,-,-,-,-
investment securities,-,-,-,-,-
investment securities growth,-,-,-,-,-
securities in custody,-,-,-,-,-
securities in custody growth,-,-,-,-,-
other investments,366.73M,330.79M,293.83M,416.31M,391.67M
"net property, plant & equipments",-,-,-,-,512.91M
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B
other assets,25.73B,26.03B,25.74B,25.43B,1.19B
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M
total assets,31.1B,32.26B,30.69B,31.23B,34.79B
total assets growth,-,3.71%,-4.87%,1.78%,11.38%
return on average assets,-,-,-,-,3.72%

In [38]:
tables[1]

,2016,2017,2018,2019,2020
total debt,22.98B,24.63B,23.31B,24.68B,27.24B
total debt growth,-,7.20%,-5.39%,5.90%,10.37%
st debt & current portion lt,2.23B,2.06B,1.42B,2.86B,2.36B
short term debt,-,-,-,-,32.79M
current portion of long term debt,2.23B,2.06B,1.42B,2.86B,2.32B
long-term debt,20.74B,22.57B,21.89B,21.82B,24.88B
lt debt excl. capitalized leases,20.74B,22.57B,21.89B,21.31B,24.4B
capitalized lease obligations,-,-,-,-,-
total debt / assets,73.87%,76.36%,75.95%,79.02%,78.30%
deferred taxes,-,-,-,-,-
other liabilities,3.03B,3.2B,3.35B,3.42B,3.89B
other liabilities (excl. deferred income),3.03B,3.2B,3.35B,3.42B,3.89B
total liabilities,26.01B,27.83B,26.66B,28.1B,31.13B
total liabilities growth,-,7.01%,-4.20%,5.41%,10.77%
preferred stock (carrying value),-,-,-,-,42.09M
redeemable preferred stock,43.41M,43.08M,42.75M,42.42M,42.09M
non-redeemable preferred stock,-,-,-,-,-
common equity (total),4.27B,3.64B,3.25B,2.48B,3B
common stock par/carry value,32K,32K,32K,32K,34K
additional paid-in capital/capital surplus,9.52B,9.61B,9.7B,9.76B,11.18B
retained earnings,(4.46B),(4.78B),(4.89B),(5.38B),(6.1B)
esop debt guarantee,-,-,-,-,-
cumulative translation adjustment/unrealized for. exch. gain,(157.86M),(118.14M),(158.9M),-,-
unrealized gain/loss marketable securities,13.36M,(370K),(46K),-,-
revaluation reserves,-,-,-,-,-
other appropriated reserves,-,-,-,-,(188.68M)
unappropriated reserves,-,-,-,-,-
treasury stock,(682.56M),(1.08B),(1.43B),(1.77B),(1.89B)
common equity / total assets,13.72%,11.29%,10.60%,7.95%,8.62%
total shareholders' equity,4.27B,3.64B,3.25B,2.48B,3.04B
total shareholders' equity / assets,13.72%,11.29%,10.60%,7.95%,8.74%
return on average assets,-,-,-,-,3.72%
accumulated minority interest,787.23M,743.08M,730.44M,603.91M,618.77M
total equity,5.05B,4.39B,3.98B,3.09B,3.66B
liabilities & shareholders' equity,31.1B,32.26B,30.69B,31.23B,34.79B

In [43]:
tables[1].iloc[0, 0]

'22.98B'

In [45]:
ticker = 'spg'
balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
urls = [balance_sheet_url, income_url, cashflow_url]
for i in urls:
    print(i)

https://www.marketwatch.com/investing/stock/spg/financials/balance-sheet
https://www.marketwatch.com/investing/stock/spg/financials
https://www.marketwatch.com/investing/stock/spg/financials/cash-flow

In [52]:
tables_list = []
for url in urls:
    tables = pd.read_html(url, match="Item", index_col=0)
    for i in range(len(tables)):
        tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
        if not tables[i].columns[-1].isdigit():
            tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
        print('Appending')
        tables_list.append(tables[i])

Appending
Appending
Appending
Appending
Appending
Appending

In [53]:
len(tables_list)

6

In [54]:
tables_list[0]

,2016,2017,2018,2019,2020
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B
cash & short term investments growth,-,164.67%,-65.30%,30.14%,51.13%
cash only,560.06M,1.48B,514.34M,669.37M,1.01B
total short-term investments,-,-,-,-,-
short-term receivables,-,-,-,-,597.6M
short term receivables growth,-,-,-,-,-
investment securities,-,-,-,-,-
investment securities growth,-,-,-,-,-
securities in custody,-,-,-,-,-
securities in custody growth,-,-,-,-,-
other investments,366.73M,330.79M,293.83M,416.31M,391.67M
"net property, plant & equipments",-,-,-,-,512.91M
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B
other assets,25.73B,26.03B,25.74B,25.43B,1.19B
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M
total assets,31.1B,32.26B,30.69B,31.23B,34.79B
total assets growth,-,3.71%,-4.87%,1.78%,11.38%
return on average assets,-,-,-,-,3.72%

In [55]:
tables_list[1]

,2016,2017,2018,2019,2020
total debt,22.98B,24.63B,23.31B,24.68B,27.24B
total debt growth,-,7.20%,-5.39%,5.90%,10.37%
st debt & current portion lt,2.23B,2.06B,1.42B,2.86B,2.36B
short term debt,-,-,-,-,32.79M
current portion of long term debt,2.23B,2.06B,1.42B,2.86B,2.32B
long-term debt,20.74B,22.57B,21.89B,21.82B,24.88B
lt debt excl. capitalized leases,20.74B,22.57B,21.89B,21.31B,24.4B
capitalized lease obligations,-,-,-,-,-
total debt / assets,73.87%,76.36%,75.95%,79.02%,78.30%
deferred taxes,-,-,-,-,-
other liabilities,3.03B,3.2B,3.35B,3.42B,3.89B
other liabilities (excl. deferred income),3.03B,3.2B,3.35B,3.42B,3.89B
total liabilities,26.01B,27.83B,26.66B,28.1B,31.13B
total liabilities growth,-,7.01%,-4.20%,5.41%,10.77%
preferred stock (carrying value),-,-,-,-,42.09M
redeemable preferred stock,43.41M,43.08M,42.75M,42.42M,42.09M
non-redeemable preferred stock,-,-,-,-,-
common equity (total),4.27B,3.64B,3.25B,2.48B,3B
common stock par/carry value,32K,32K,32K,32K,34K
additional paid-in capital/capital surplus,9.52B,9.61B,9.7B,9.76B,11.18B
retained earnings,(4.46B),(4.78B),(4.89B),(5.38B),(6.1B)
esop debt guarantee,-,-,-,-,-
cumulative translation adjustment/unrealized for. exch. gain,(157.86M),(118.14M),(158.9M),-,-
unrealized gain/loss marketable securities,13.36M,(370K),(46K),-,-
revaluation reserves,-,-,-,-,-
other appropriated reserves,-,-,-,-,(188.68M)
unappropriated reserves,-,-,-,-,-
treasury stock,(682.56M),(1.08B),(1.43B),(1.77B),(1.89B)
common equity / total assets,13.72%,11.29%,10.60%,7.95%,8.62%
total shareholders' equity,4.27B,3.64B,3.25B,2.48B,3.04B
total shareholders' equity / assets,13.72%,11.29%,10.60%,7.95%,8.74%
return on average assets,-,-,-,-,3.72%
accumulated minority interest,787.23M,743.08M,730.44M,603.91M,618.77M
total equity,5.05B,4.39B,3.98B,3.09B,3.66B
liabilities & shareholders' equity,31.1B,32.26B,30.69B,31.23B,34.79B

In [56]:
tables_list[2]

,2016,2017,2018,2019,2020
sales/revenue,5.44B,5.54B,5.66B,5.68B,4.61B
sales growth,-,1.90%,2.15%,0.42%,-18.90%
total investment income,-,-,-,-,-
sundry revenue/income,420.42M,418.24M,486.87M,437.72M,208.25M
trading account income,-,-,-,-,-
"trust income, commissions & fees",-,-,-,-,96.88M
commission & fee income,-,-,-,-,96.88M
total expense,3.58B,3.55B,3.56B,3.64B,2.64B
total interest expense,857.55M,809.39M,815.92M,789.35M,784.4M
depreciation & amortization expense,1.25B,1.28B,1.28B,1.34B,1.32B
other operating expense,116.97M,131.48M,109.32M,109.9M,80.86M
operating income,1.86B,1.99B,2.09B,2.04B,1.97B
operating income growth,-,7.12%,5.23%,-2.45%,-3.48%
non-operating income (expense),(12.23M),9.42M,7.02M,13.42M,-
non-operating interest income,-,-,-,-,-
miscellaneous non operating expense,(12.23M),9.42M,7.02M,13.42M,-
equity in affiliates (pretax),-,-,-,-,-
unusual expense,136.78M,128.62M,-,58.76M,-
pretax income,1.71B,1.87B,2.1B,2B,1.19B
pretax income growth,-,9.48%,12.31%,-4.93%,-40.56%
pretax margin,-,-,-,-,25.77%
income taxes,29.68M,23.34M,36.9M,30.05M,(4.64M)
income tax - current domestic,-,-,-,-,-
income tax - current foreign,-,-,-,-,-
income tax - deferred domestic,-,-,-,-,-
income tax - deferred foreign,-,-,-,-,-
income tax credits,-,-,-,-,-
equity in affiliates,353.33M,400.27M,475.25M,444.35M,200.24M
other after tax income (expense),-,-,-,-,-
consolidated net income,2.03B,2.25B,2.54B,2.41B,1.39B
minority interest expense,(295.81M),(296.94M),382.29M,321.6M,164.76M
net income,2.33B,2.54B,2.16B,2.09B,1.23B
net income growth,-,9.30%,-15.23%,-3.11%,-41.27%
net margin growth,-,-,-,-,26.64%
extraordinaries & discontinued operations,84.55M,3.65M,288.83M,6.67M,(114.96M)
extra items & gain/loss sale of assets,84.55M,3.65M,288.83M,6.67M,(114.96M)
cumulative effect - accounting chg,-,-,-,-,-
discontinued operations,-,-,-,-,-
net income after extraordinaries,2.41B,2.55B,2.45B,2.1B,1.11B
preferred dividends,3.34M,3.34M,3.34M,3.34M,3.34M
net income available to common,2.32B,2.54B,2.15B,2.09B,1.22B
eps (basic),5.6,6.23,6.94,6.77,3.22
eps (basic) growth,-,11.27%,11.34%,-2.48%,-52.40%
basic shares outstanding,312.69M,311.52M,309.63M,307.95M,308.74M
eps (diluted),5.6,6.23,6.94,6.77,3.22
eps (diluted) growth,-,11.27%,11.34%,-2.48%,-52.40%
diluted shares outstanding,312.69M,311.52M,309.63M,307.95M,308.74M

In [57]:
tables_list[3]

,2016,2017,2018,2019,2020
funds from operations,4.1B,4.06B,4.5B,4.09B,2.89B
funds from operations growth,-,-0.83%,10.69%,-9.07%,-29.38%
changes in working capital,(105.31M),(59.18M),(8.65M),(36.4M),(425.02M)
receivables,-,-,-,-,(415.91M)
inventories,-,-,-,-,-
accounts payable,-,199.86M,168.61M,-,-
other assets/liabilities,(105.31M),(159.12M),(92.96M),(36.4M),(9.11M)
net operating cash flow,3.91B,4B,4.2B,4.04B,2.58B
net operating cash flow growth,-,2.38%,4.99%,-3.85%,-36.16%

In [58]:
tables_list[4]

,2016,2017,2018,2019,2020
capital expenditures,(1.3B),(996.59M),(832.97M),(888.81M),(484.12M)
capital expenditures growth,-,23.25%,16.42%,-6.70%,45.53%
capital expenditures (fixed assets),(798.47M),(732.1M),(781.91M),(876.01M),(484.12M)
capital expenditures (other assets),(499.98M),(264.49M),(51.06M),(12.8M),-
net assets from acquisitions,-,-,-,-,(3.61B)
sale of fixed assets & businesses,1.51M,382K,161K,139K,-
purchase/sale of investments,(300.16M),(197.44M),(64.6M),(430.38M),(202.34M)
purchase of investments,(350.97M),(253.71M),(89.6M),(438.02M),(232.56M)
sale/maturity of investments,50.81M,56.27M,25M,7.64M,30.22M
other uses,-,-,-,-,-
other sources,96.55M,27.48M,213.6M,13.48M,64.62M
net investing cash flow,(1.5B),(1.17B),(683.81M),(1.31B),(4.23B)

In [18]:
tables_list[5]

,2016,2017,2018,2019,2020
cash dividends paid - total,(2.36B),(2.57B),(2.82B),(2.95B),(1.66B)
cash dividends growth,NaN,-9.16%,-9.72%,-4.53%,43.58%
common dividends,(2.35B),(2.57B),(2.82B),(2.95B),(1.66B)
preferred dividends,(1.92M),(1.92M),(1.92M),(1.92M),(1.92M)
change in capital stock,(328K),(328K),(81.84M),(10.13M),(1.72B)
repurchase of common & preferred stk.,(328K),(328K),(81.84M),(10.13M),(1.72B)
sale of common & preferred stock,NaN,NaN,NaN,NaN,NaN
proceeds from stock options,NaN,NaN,NaN,NaN,NaN
other proceeds from sale of stock,NaN,NaN,NaN,NaN,NaN
"issuance/reduction of debt, net",216.04M,1.21B,(1.14B),784.63M,15.22B
change in current debt,NaN,NaN,NaN,NaN,NaN
change in long-term debt,NaN,NaN,NaN,NaN,15.22B
issuance of long-term debt,NaN,NaN,NaN,NaN,15.23B
reduction in long-term debt,NaN,NaN,NaN,NaN,(12.96M)
other funds,(146.51M),(139.91M),(76.96M),(41.55M),(9.13M)
other uses,(146.51M),(139.91M),(76.96M),(41.55M),(9.13M)
other sources,NaN,NaN,NaN,NaN,NaN
net financing cash flow,(2.29B),(1.5B),(4.13B),(2.22B),1.99B
net financing cash flow growth,NaN,34.37%,-174.91%,46.27%,189.95%
exchange rate effect,NaN,NaN,NaN,NaN,NaN
miscellaneous funds,(259.57M),(409.79M),(357.02M),(359.77M),NaN
net change in cash,(141.08M),922.25M,(967.97M),155.04M,342.24M
free cash flow,3.11B,3.27B,3.42B,3.16B,2.09B
free cash flow growth,NaN,5.13%,4.58%,-7.48%,-33.78%
free cash flow yield,NaN,NaN,NaN,NaN,1.63

In [1]:
#
import requests
import datetime as dt
import math
from bs4 import BeautifulSoup
import numpy as np
import re
import pandas as pd

In [41]:
%%timeit
ticker = 'spg'
balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
urls = [balance_sheet_url, income_url, cashflow_url]
tables_list = []
for url in urls:
    tables = pd.read_html(url, match="Item", index_col=0)
    for i in range(len(tables)):
        tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
        if not tables[i].columns[-1].isdigit():
            tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
        tables_list.append(tables[i].replace("-", np.nan))

1.9 s ± 346 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [3]:
tables_list[5]

,2016,2017,2018,2019,2020
cash dividends paid - total,(2.36B),(2.57B),(2.82B),(2.95B),(1.66B)
cash dividends growth,NaN,-9.16%,-9.72%,-4.53%,43.58%
common dividends,(2.35B),(2.57B),(2.82B),(2.95B),(1.66B)
preferred dividends,(1.92M),(1.92M),(1.92M),(1.92M),(1.92M)
change in capital stock,(328K),(328K),(81.84M),(10.13M),(1.72B)
repurchase of common & preferred stk.,(328K),(328K),(81.84M),(10.13M),(1.72B)
sale of common & preferred stock,NaN,NaN,NaN,NaN,NaN
proceeds from stock options,NaN,NaN,NaN,NaN,NaN
other proceeds from sale of stock,NaN,NaN,NaN,NaN,NaN
"issuance/reduction of debt, net",216.04M,1.21B,(1.14B),784.63M,15.22B
change in current debt,NaN,NaN,NaN,NaN,NaN
change in long-term debt,NaN,NaN,NaN,NaN,15.22B
issuance of long-term debt,NaN,NaN,NaN,NaN,15.23B
reduction in long-term debt,NaN,NaN,NaN,NaN,(12.96M)
other funds,(146.51M),(139.91M),(76.96M),(41.55M),(9.13M)
other uses,(146.51M),(139.91M),(76.96M),(41.55M),(9.13M)
other sources,NaN,NaN,NaN,NaN,NaN
net financing cash flow,(2.29B),(1.5B),(4.13B),(2.22B),1.99B
net financing cash flow growth,NaN,34.37%,-174.91%,46.27%,189.95%
exchange rate effect,NaN,NaN,NaN,NaN,NaN
miscellaneous funds,(259.57M),(409.79M),(357.02M),(359.77M),NaN
net change in cash,(141.08M),922.25M,(967.97M),155.04M,342.24M
free cash flow,3.11B,3.27B,3.42B,3.16B,2.09B
free cash flow growth,NaN,5.13%,4.58%,-7.48%,-33.78%
free cash flow yield,NaN,NaN,NaN,NaN,1.63

In [34]:
pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
           'B': ' * 1000000000',  # convert B to ' * 1000000000'
           'M': ' * 1000000',     # convert M to ' * 1000000'
           'K': ' * 1000',        # convert K to ' * 1000'
           '%': ' / 100'          # convert % to ' / 100'
          }
tables_list[5].replace(pattern, regex=True).applymap(pd.eval, na_action='ignore')

,2016,2017,2018,2019,2020
cash dividends paid - total,-2.360000e+09,-2.570000e+09,-2.820000e+09,-2.950000e+09,-1.660000e+09
cash dividends growth,NaN,-9.160000e-02,-9.720000e-02,-4.530000e-02,4.358000e-01
common dividends,-2.350000e+09,-2.570000e+09,-2.820000e+09,-2.950000e+09,-1.660000e+09
preferred dividends,-1.920000e+06,-1.920000e+06,-1.920000e+06,-1.920000e+06,-1.920000e+06
change in capital stock,-3.280000e+05,-3.280000e+05,-8.184000e+07,-1.013000e+07,-1.720000e+09
repurchase of common & preferred stk.,-3.280000e+05,-3.280000e+05,-8.184000e+07,-1.013000e+07,-1.720000e+09
sale of common & preferred stock,NaN,NaN,NaN,NaN,NaN
proceeds from stock options,NaN,NaN,NaN,NaN,NaN
other proceeds from sale of stock,NaN,NaN,NaN,NaN,NaN
"issuance/reduction of debt, net",2.160400e+08,1.210000e+09,-1.140000e+09,7.846300e+08,1.522000e+10
change in current debt,NaN,NaN,NaN,NaN,NaN
change in long-term debt,NaN,NaN,NaN,NaN,1.522000e+10
issuance of long-term debt,NaN,NaN,NaN,NaN,1.523000e+10
reduction in long-term debt,NaN,NaN,NaN,NaN,-1.296000e+07
other funds,-1.465100e+08,-1.399100e+08,-7.696000e+07,-4.155000e+07,-9.130000e+06
other uses,-1.465100e+08,-1.399100e+08,-7.696000e+07,-4.155000e+07,-9.130000e+06
other sources,NaN,NaN,NaN,NaN,NaN
net financing cash flow,-2.290000e+09,-1.500000e+09,-4.130000e+09,-2.220000e+09,1.990000e+09
net financing cash flow growth,NaN,3.437000e-01,-1.749100e+00,4.627000e-01,1.899500e+00
exchange rate effect,NaN,NaN,NaN,NaN,NaN
miscellaneous funds,-2.595700e+08,-4.097900e+08,-3.570200e+08,-3.597700e+08,NaN
net change in cash,-1.410800e+08,9.222500e+08,-9.679700e+08,1.550400e+08,3.422400e+08
free cash flow,3.110000e+09,3.270000e+09,3.420000e+09,3.160000e+09,2.090000e+09
free cash flow growth,NaN,5.130000e-02,4.580000e-02,-7.480000e-02,-3.378000e-01
free cash flow yield,NaN,NaN,NaN,NaN,1.630000e+00

In [63]:
#%timeit tables_list[5][tables_list[5].index.str.match("^free.*growth$")==True]

1.02 ms ± 32.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [3]:
tables_list[5][tables_list[5].index.str.match("^free.*growth$")==True]

                      2016   2017   2018    2019     2020
free cash flow growth    -  5.13%  4.58%  -7.48%  -33.78%

In [4]:
tables_list[5][tables_list[5].index.str.match("^free.*growth$")==True].values

array([['-', '5.13%', '4.58%', '-7.48%', '-33.78%']], dtype=object)

In [50]:
tables_list[5][tables_list[5].index.str.match("^free.*growth$")==True].values.tolist()

[[nan, '5.13%', '4.58%', '-7.48%', '-33.78%']]

In [6]:
tables_list[5][tables_list[5].index.str.match("^free.*growth$")==True].values.tolist()[0]

['-', '5.13%', '4.58%', '-7.48%', '-33.78%']

In [65]:
%timeit tables_list[5].loc["free cash flow growth"]

453 µs ± 133 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [66]:
tables_list[5].loc["free cash flow growth"]

2016          -
2017      5.13%
2018      4.58%
2019     -7.48%
2020    -33.78%
Name: free cash flow growth, dtype: object

In [50]:
#
ticker = 'aapl'
balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
urls = [balance_sheet_url, income_url, cashflow_url]
tables_list = []  # list for all table dataframes
pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
           'B': ' * 1000000000',  # convert B to ' * 1000000000'
           'M': ' * 1000000',     # convert M to ' * 1000000'
           'K': ' * 1000',        # convert K to ' * 1000'
           '%': ' / 100'          # convert % to ' / 100'
          }
for url in urls:
    tables = pd.read_html(url, match="Item", index_col=0) # Scrape only tables with word 'Item' in it
    for i in range(len(tables)):
        # remove the duplicate from index.
        tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
        if not tables[i].columns[-1].isdigit(): # If a column has no digit character, drop it
            tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
        # 1. replace '-' with np.nan
        # 2. replace according regex patern dictionary
        # 3. evaluate the arithmetic symbols with pd.eval
        tables_list.append(tables[i].replace("-", np.nan).replace(pattern, regex=True).applymap(pd.eval, na_action='ignore'))

In [3]:
tables_list[5]

,2016,2017,2018,2019,2020
cash dividends paid - total,-2.360000e+09,-2.570000e+09,-2.820000e+09,-2.950000e+09,-1.660000e+09
cash dividends growth,NaN,-9.160000e-02,-9.720000e-02,-4.530000e-02,4.358000e-01
common dividends,-2.350000e+09,-2.570000e+09,-2.820000e+09,-2.950000e+09,-1.660000e+09
preferred dividends,-1.920000e+06,-1.920000e+06,-1.920000e+06,-1.920000e+06,-1.920000e+06
change in capital stock,-3.280000e+05,-3.280000e+05,-8.184000e+07,-1.013000e+07,-1.720000e+09
repurchase of common & preferred stk.,-3.280000e+05,-3.280000e+05,-8.184000e+07,-1.013000e+07,-1.720000e+09
sale of common & preferred stock,NaN,NaN,NaN,NaN,NaN
proceeds from stock options,NaN,NaN,NaN,NaN,NaN
other proceeds from sale of stock,NaN,NaN,NaN,NaN,NaN
"issuance/reduction of debt, net",2.160400e+08,1.210000e+09,-1.140000e+09,7.846300e+08,1.522000e+10
change in current debt,NaN,NaN,NaN,NaN,NaN
change in long-term debt,NaN,NaN,NaN,NaN,1.522000e+10
issuance of long-term debt,NaN,NaN,NaN,NaN,1.523000e+10
reduction in long-term debt,NaN,NaN,NaN,NaN,-1.296000e+07
other funds,-1.465100e+08,-1.399100e+08,-7.696000e+07,-4.155000e+07,-9.130000e+06
other uses,-1.465100e+08,-1.399100e+08,-7.696000e+07,-4.155000e+07,-9.130000e+06
other sources,NaN,NaN,NaN,NaN,NaN
net financing cash flow,-2.290000e+09,-1.500000e+09,-4.130000e+09,-2.220000e+09,1.990000e+09
net financing cash flow growth,NaN,3.437000e-01,-1.749100e+00,4.627000e-01,1.899500e+00
exchange rate effect,NaN,NaN,NaN,NaN,NaN
miscellaneous funds,-2.595700e+08,-4.097900e+08,-3.570200e+08,-3.597700e+08,NaN
net change in cash,-1.410800e+08,9.222500e+08,-9.679700e+08,1.550400e+08,3.422400e+08
free cash flow,3.110000e+09,3.270000e+09,3.420000e+09,3.160000e+09,2.090000e+09
free cash flow growth,NaN,5.130000e-02,4.580000e-02,-7.480000e-02,-3.378000e-01
free cash flow yield,NaN,NaN,NaN,NaN,1.630000e+00

In [39]:
%%timeit
ticker = 'spg'
balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
urls = [balance_sheet_url, income_url, cashflow_url]
tables_list = []  # list for all table dataframes
pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
           'B': ' * 1000000000',  # convert B to ' * 1000000000'
           'M': ' * 1000000',     # convert M to ' * 1000000'
           'K': ' * 1000',        # convert K to ' * 1000'
           '%': ' / 100'          # convert % to ' / 100'
          }
for url in urls:
    tables = pd.read_html(url, match="Item", index_col=0) # Scrape only tables with word 'Item' in it
    for i in range(len(tables)):
        # remove the duplicate from index.
        tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
        if not tables[i].columns[-1].isdigit(): # If a column has no digit character, drop it
            tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
        # 1. replace '-' with np.nan
        # 2. replace according regex patern dictionary
        # 3. evaluate the arithmetic symbols with pd.eval
        tables_list.append(tables[i].replace("-", np.nan).replace(pattern, regex=True).applymap(pd.eval, na_action='ignore'))

3.17 s ± 500 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [42]:
tables_list[0]

,2016,2017,2018,2019,2020
cash & short term investments,560.06M,1.48B,514.34M,669.37M,1.01B
cash & short term investments growth,NaN,164.67%,-65.30%,30.14%,51.13%
cash only,560.06M,1.48B,514.34M,669.37M,1.01B
total short-term investments,NaN,NaN,NaN,NaN,NaN
short-term receivables,NaN,NaN,NaN,NaN,597.6M
short term receivables growth,NaN,NaN,NaN,NaN,NaN
investment securities,NaN,NaN,NaN,NaN,NaN
investment securities growth,NaN,NaN,NaN,NaN,NaN
securities in custody,NaN,NaN,NaN,NaN,NaN
securities in custody growth,NaN,NaN,NaN,NaN,NaN
other investments,366.73M,330.79M,293.83M,416.31M,391.67M
"net property, plant & equipments",NaN,NaN,NaN,NaN,512.91M
other assets (including intangibles),26.01B,26.24B,25.89B,25.53B,1.24B
other assets,25.73B,26.03B,25.74B,25.43B,1.19B
intangible assets,285.14M,208.56M,150.74M,95.85M,55.06M
total assets,31.1B,32.26B,30.69B,31.23B,34.79B
total assets growth,NaN,3.71%,-4.87%,1.78%,11.38%
return on average assets,NaN,NaN,NaN,NaN,3.72%

In [43]:
tables_list[1]

,2016,2017,2018,2019,2020
total debt,22.98B,24.63B,23.31B,24.68B,27.24B
total debt growth,NaN,7.20%,-5.39%,5.90%,10.37%
st debt & current portion lt,2.23B,2.06B,1.42B,2.86B,2.36B
short term debt,NaN,NaN,NaN,NaN,32.79M
current portion of long term debt,2.23B,2.06B,1.42B,2.86B,2.32B
long-term debt,20.74B,22.57B,21.89B,21.82B,24.88B
lt debt excl. capitalized leases,20.74B,22.57B,21.89B,21.31B,24.4B
capitalized lease obligations,NaN,NaN,NaN,NaN,NaN
total debt / assets,73.87%,76.36%,75.95%,79.02%,78.30%
deferred taxes,NaN,NaN,NaN,NaN,NaN
other liabilities,3.03B,3.2B,3.35B,3.42B,3.89B
other liabilities (excl. deferred income),3.03B,3.2B,3.35B,3.42B,3.89B
total liabilities,26.01B,27.83B,26.66B,28.1B,31.13B
total liabilities growth,NaN,7.01%,-4.20%,5.41%,10.77%
preferred stock (carrying value),NaN,NaN,NaN,NaN,42.09M
redeemable preferred stock,43.41M,43.08M,42.75M,42.42M,42.09M
non-redeemable preferred stock,NaN,NaN,NaN,NaN,NaN
common equity (total),4.27B,3.64B,3.25B,2.48B,3B
common stock par/carry value,32K,32K,32K,32K,34K
additional paid-in capital/capital surplus,9.52B,9.61B,9.7B,9.76B,11.18B
retained earnings,(4.46B),(4.78B),(4.89B),(5.38B),(6.1B)
esop debt guarantee,NaN,NaN,NaN,NaN,NaN
cumulative translation adjustment/unrealized for. exch. gain,(157.86M),(118.14M),(158.9M),NaN,NaN
unrealized gain/loss marketable securities,13.36M,(370K),(46K),NaN,NaN
revaluation reserves,NaN,NaN,NaN,NaN,NaN
other appropriated reserves,NaN,NaN,NaN,NaN,(188.68M)
unappropriated reserves,NaN,NaN,NaN,NaN,NaN
treasury stock,(682.56M),(1.08B),(1.43B),(1.77B),(1.89B)
common equity / total assets,13.72%,11.29%,10.60%,7.95%,8.62%
total shareholders' equity,4.27B,3.64B,3.25B,2.48B,3.04B
total shareholders' equity / assets,13.72%,11.29%,10.60%,7.95%,8.74%
return on average assets,NaN,NaN,NaN,NaN,3.72%
accumulated minority interest,787.23M,743.08M,730.44M,603.91M,618.77M
total equity,5.05B,4.39B,3.98B,3.09B,3.66B
liabilities & shareholders' equity,31.1B,32.26B,30.69B,31.23B,34.79B

In [52]:
tables_list[1].loc['total shareholders\' equity']

2016    4.27B
2017    3.64B
2018    3.25B
2019    2.48B
2020    3.04B
Name: total shareholders' equity, dtype: object

In [59]:
type(tables_list[1].loc['total shareholders\' equity'])

pandas.core.series.Series

In [47]:
tables_list[1].loc['total shareholders\' equity'].values.tolist()

['4.27B', '3.64B', '3.25B', '2.48B', '3.04B']

In [61]:
%timeit tables_list[1].loc['total shareholders\' equity'].values.tolist()

340 µs ± 38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [57]:
tables_list[1][tables_list[1].index.str.match("^total shareholder.*equity$")==True]

                             2016   2017   2018   2019   2020
total shareholders' equity  4.27B  3.64B  3.25B  2.48B  3.04B

In [58]:
type(tables_list[1][tables_list[1].index.str.match("^total shareholder.*equity$")==True])

pandas.core.frame.DataFrame

In [56]:
tables_list[1][tables_list[1].index.str.match("^total shareholder.*equity$")==True].values.tolist()

[['4.27B', '3.64B', '3.25B', '2.48B', '3.04B']]

In [60]:
%timeit tables_list[1][tables_list[1].index.str.match("^total shareholder.*equity$")==True].values.tolist()

2.43 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [41]:
tables_list[2]

,2016,2017,2018,2019,2020
sales/revenue,2.142300e+11,2.285700e+11,2.658100e+11,2.599700e+11,2.741500e+11
sales growth,NaN,6.700000e-02,1.629000e-01,-2.200000e-02,5.460000e-02
cost of goods sold (cogs) incl. d&a,1.315100e+11,1.417000e+11,1.638300e+11,1.622600e+11,1.701400e+11
cogs growth,NaN,7.750000e-02,1.561000e-01,-9.500000e-03,4.860000e-02
cogs excluding d&a,1.217100e+11,1.323000e+11,1.545300e+11,1.509600e+11,1.590900e+11
depreciation & amortization expense,9.800000e+09,9.400000e+09,9.300000e+09,1.130000e+10,1.106000e+10
depreciation,8.300000e+09,8.200000e+09,9.300000e+09,1.130000e+10,1.106000e+10
amortization of intangibles,1.500000e+09,1.200000e+09,NaN,NaN,NaN
gross income,8.272000e+10,8.687000e+10,1.019800e+11,9.770000e+10,1.040100e+11
gross income growth,NaN,5.020000e-02,1.740000e-01,-4.200000e-02,6.450000e-02
gross profit margin,NaN,NaN,NaN,NaN,3.794000e-01
sg&a expense,2.424000e+10,2.684000e+10,3.094000e+10,3.446000e+10,3.867000e+10
sga growth,NaN,1.074000e-01,1.527000e-01,1.138000e-01,1.220000e-01
research & development,1.005000e+10,1.158000e+10,1.424000e+10,1.622000e+10,1.875000e+10
other sg&a,1.419000e+10,1.526000e+10,1.671000e+10,1.825000e+10,1.992000e+10
other operating expense,NaN,NaN,NaN,NaN,NaN
unusual expense,-5.480000e+08,NaN,NaN,NaN,-4.650000e+08
ebit after unusual expense,5.903000e+10,NaN,NaN,NaN,6.580000e+10
non operating income/expense,-2.000000e+08,1.180000e+09,-5.850000e+08,1.110000e+09,3.970000e+08
non-operating interest income,-2.949673e+08,5.200000e+09,5.690000e+09,4.960000e+09,3.760000e+09
equity in affiliates (pretax),NaN,NaN,NaN,NaN,NaN
interest expense,1.460000e+09,2.320000e+09,3.240000e+09,3.580000e+09,2.870000e+09
interest expense growth,NaN,5.955000e-01,3.947000e-01,1.037000e-01,-1.966000e-01
gross interest expense,1.460000e+09,2.320000e+09,3.240000e+09,3.580000e+09,2.870000e+09
interest capitalized,NaN,NaN,NaN,NaN,NaN
pretax income,6.137000e+10,6.409000e+10,7.290000e+10,6.574000e+10,6.709000e+10
pretax income growth,NaN,4.430000e-02,1.375000e-01,-9.830000e-02,2.060000e-02
pretax margin,NaN,NaN,NaN,NaN,2.447000e-01
income tax,1.569000e+10,1.574000e+10,1.337000e+10,1.048000e+10,9.680000e+09
income tax - current domestic,8.640000e+09,8.100000e+09,4.198000e+10,6.860000e+09,6.760000e+09
income tax - current foreign,2.110000e+09,1.670000e+09,3.990000e+09,3.960000e+09,3.130000e+09
income tax - deferred domestic,4.910000e+09,5.980000e+09,-3.377000e+10,-3.010000e+09,-3.600000e+09
income tax - deferred foreign,3.300000e+07,-1.600000e+07,1.180000e+09,2.670000e+09,3.380000e+09
income tax credits,NaN,NaN,NaN,NaN,NaN
equity in affiliates,NaN,NaN,NaN,NaN,NaN
other after tax income (expense),NaN,NaN,NaN,NaN,NaN
consolidated net income,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
minority interest expense,NaN,NaN,NaN,NaN,NaN
net income,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
net income growth,NaN,5.830000e-02,2.312000e-01,-7.180000e-02,3.900000e-02
net margin growth,NaN,NaN,NaN,NaN,2.094000e-01
extraordinaries & discontinued operations,NaN,NaN,NaN,NaN,NaN
extra items & gain/loss sale of assets,NaN,NaN,NaN,NaN,NaN
cumulative effect - accounting chg,NaN,NaN,NaN,NaN,NaN
discontinued operations,NaN,NaN,NaN,NaN,NaN
net income after extraordinaries,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
preferred dividends,NaN,NaN,NaN,NaN,NaN
net income available to common,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
eps (basic),2.090000e+00,2.320000e+00,3.000000e+00,2.990000e+00,3.310000e+00
eps (basic) growth,NaN,1.102000e-01,2.956000e-01,-3.700000e-03,1.060000e-01
basic shares outstanding,2.188000e+10,2.087000e+10,1.982000e+10,1.847000e+10,1.735000e+10
eps (diluted),2.080000e+00,2.300000e+00,2.980000e+00,2.970000e+00,3.280000e+00
eps (diluted) growth,NaN,1.083000e-01,2.932000e-01,-2.000000e-03,1.023000e-01
diluted shares outstanding,5.251635e+08,2.101000e+10,-1.474836e+09,1.860000e+10,1.753000e+10
ebitda,6.828000e+10,6.943000e+10,8.034000e+10,7.454000e+10,7.640000e+10
ebitda growth,NaN,1.680000e-02,1.572000e-01,-7.220000e-02,2.490000e-02
ebitda margin,NaN,NaN,NaN,NaN,2.787000e-01

In [49]:
tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index', inplace=True)
shareholderequity = tables_list[1].loc['total shareholders\' equity'].values.tolist()
longtermdebt = tables_list[1].loc['long-term debt'].values.tolist()
eps = tables_list[2].loc['eps (basic)'].values.tolist()
epsgrowth = tables_list[2].loc['eps (basic) growth'].values.tolist()
netincome = tables_list[2].loc['net income'].values.tolist()
roa = tables_list[1].loc['total shareholders\' equity / assets'].values.tolist()
try:
    interestexpense = tables_list[2].loc['total interest expense'].values.tolist()
except:
    interestexpense = tables_list[2].loc['interest expense'].values.tolist()
if 'ebitda' in tables_list[2].index:
    ebitda = tables_list[2].loc['ebitda'].values.tolist()
else:
    ebitda = (tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense'].values).tolist()
ebitda2 = ebitda = (tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense'].values).tolist()
print(shareholderequity)
print(longtermdebt)
print(eps)
print(epsgrowth)
print(netincome)
print(roa)
print(interestexpense)
print(ebitda)
print(ebitda2)
#eps, epsgrowth, netincome, roa, interestexpense, ebitda

[128250000000.0, 134050000000.00002, 107150000000.0, 90490000000.0, 65340000000.0]
[75430000000.0, 97210000000.0, 93740000000.0, 91810000000.0, 107050000000.0]
[2.09, 2.32, 3.0, 2.99, 3.31]
[nan, 0.11019999999999999, 0.2956, -0.0037, 0.106]
[45690000000.0, 48350000000.0, 59530000000.0, 55260000000.0, 57410000000.0]
[0.3987, 0.35719999999999996, 0.293, 0.2673, 0.20170000000000002]
[1460000000.0, 2320000000.0, 3240000000.0, 3580000000.0, 2870000000.0]
[18740000000.0, 20890000000.0, 33620000000.0, 29900000000.0, 33800000000.0]
[18740000000.0, 20890000000.0, 33620000000.0, 29900000000.0, 33800000000.0]

In [20]:
tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income taxes'].values - tables_list[2].loc['depreciation & amortization expense'].values

array([ 1.9277e+08,  4.2727e+08,  2.7180e+07, -6.9400e+07, -8.6976e+08])

In [48]:
#
tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index', inplace=True)
def define_ebitda():
    if 'ebitda' in tables_list[2].index:
        return tables_list[2].loc['ebitda']
    else:
        return tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense']
pd.DataFrame({'shareholderequity': tables_list[1].loc['total shareholders\' equity'],
              'longtermdebt': tables_list[1].loc['long-term debt'],
              'eps': tables_list[2].loc['eps (basic)'],
              'epsgrowth': tables_list[2].loc['eps (basic) growth'],
              'netincome': tables_list[2].loc['net income'],
              'roa': tables_list[1].loc['total shareholders\' equity / assets'],
              'netincome': tables_list[2].loc['net income'],
              'interestexpense': tables_list[2].loc['total interest expense'],
              'ebitda': define_ebitda()
             })

,shareholderequity,longtermdebt,eps,epsgrowth,netincome,roa,interestexpense,ebitda
2016,1.282500e+11,7.543000e+10,2.09,NaN,4.569000e+10,0.3987,1.460000e+09,6.828000e+10
2017,1.340500e+11,9.721000e+10,2.32,0.1102,4.835000e+10,0.3572,2.320000e+09,6.943000e+10
2018,1.071500e+11,9.374000e+10,3.00,0.2956,5.953000e+10,0.2930,3.240000e+09,8.034000e+10
2019,9.049000e+10,9.181000e+10,2.99,-0.0037,5.526000e+10,0.2673,3.580000e+09,7.454000e+10
2020,6.534000e+10,1.070500e+11,3.31,0.1060,5.741000e+10,0.2017,2.870000e+09,7.640000e+10

In [33]:
'interest expense' in tables_list[2].index

True

In [37]:
tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index')

,2016,2017,2018,2019,2020
sales/revenue,2.142300e+11,2.285700e+11,2.658100e+11,2.599700e+11,2.741500e+11
sales growth,NaN,6.700000e-02,1.629000e-01,-2.200000e-02,5.460000e-02
cost of goods sold (cogs) incl. d&a,1.315100e+11,1.417000e+11,1.638300e+11,1.622600e+11,1.701400e+11
cogs growth,NaN,7.750000e-02,1.561000e-01,-9.500000e-03,4.860000e-02
cogs excluding d&a,1.217100e+11,1.323000e+11,1.545300e+11,1.509600e+11,1.590900e+11
depreciation & amortization expense,9.800000e+09,9.400000e+09,9.300000e+09,1.130000e+10,1.106000e+10
depreciation,8.300000e+09,8.200000e+09,9.300000e+09,1.130000e+10,1.106000e+10
amortization of intangibles,1.500000e+09,1.200000e+09,NaN,NaN,NaN
gross income,8.272000e+10,8.687000e+10,1.019800e+11,9.770000e+10,1.040100e+11
gross income growth,NaN,5.020000e-02,1.740000e-01,-4.200000e-02,6.450000e-02
gross profit margin,NaN,NaN,NaN,NaN,3.794000e-01
sg&a expense,2.424000e+10,2.684000e+10,3.094000e+10,3.446000e+10,3.867000e+10
sga growth,NaN,1.074000e-01,1.527000e-01,1.138000e-01,1.220000e-01
research & development,1.005000e+10,1.158000e+10,1.424000e+10,1.622000e+10,1.875000e+10
other sg&a,1.419000e+10,1.526000e+10,1.671000e+10,1.825000e+10,1.992000e+10
other operating expense,NaN,NaN,NaN,NaN,NaN
unusual expense,-5.480000e+08,NaN,NaN,NaN,-4.650000e+08
ebit after unusual expense,5.903000e+10,NaN,NaN,NaN,6.580000e+10
non operating income/expense,-2.000000e+08,1.180000e+09,-5.850000e+08,1.110000e+09,3.970000e+08
non-operating interest income,-2.949673e+08,5.200000e+09,5.690000e+09,4.960000e+09,3.760000e+09
equity in affiliates (pretax),NaN,NaN,NaN,NaN,NaN
total interest expense,1.460000e+09,2.320000e+09,3.240000e+09,3.580000e+09,2.870000e+09
interest expense growth,NaN,5.955000e-01,3.947000e-01,1.037000e-01,-1.966000e-01
gross interest expense,1.460000e+09,2.320000e+09,3.240000e+09,3.580000e+09,2.870000e+09
interest capitalized,NaN,NaN,NaN,NaN,NaN
pretax income,6.137000e+10,6.409000e+10,7.290000e+10,6.574000e+10,6.709000e+10
pretax income growth,NaN,4.430000e-02,1.375000e-01,-9.830000e-02,2.060000e-02
pretax margin,NaN,NaN,NaN,NaN,2.447000e-01
income tax,1.569000e+10,1.574000e+10,1.337000e+10,1.048000e+10,9.680000e+09
income tax - current domestic,8.640000e+09,8.100000e+09,4.198000e+10,6.860000e+09,6.760000e+09
income tax - current foreign,2.110000e+09,1.670000e+09,3.990000e+09,3.960000e+09,3.130000e+09
income tax - deferred domestic,4.910000e+09,5.980000e+09,-3.377000e+10,-3.010000e+09,-3.600000e+09
income tax - deferred foreign,3.300000e+07,-1.600000e+07,1.180000e+09,2.670000e+09,3.380000e+09
income tax credits,NaN,NaN,NaN,NaN,NaN
equity in affiliates,NaN,NaN,NaN,NaN,NaN
other after tax income (expense),NaN,NaN,NaN,NaN,NaN
consolidated net income,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
minority interest expense,NaN,NaN,NaN,NaN,NaN
net income,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
net income growth,NaN,5.830000e-02,2.312000e-01,-7.180000e-02,3.900000e-02
net margin growth,NaN,NaN,NaN,NaN,2.094000e-01
extraordinaries & discontinued operations,NaN,NaN,NaN,NaN,NaN
extra items & gain/loss sale of assets,NaN,NaN,NaN,NaN,NaN
cumulative effect - accounting chg,NaN,NaN,NaN,NaN,NaN
discontinued operations,NaN,NaN,NaN,NaN,NaN
net income after extraordinaries,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
preferred dividends,NaN,NaN,NaN,NaN,NaN
net income available to common,4.569000e+10,4.835000e+10,5.953000e+10,5.526000e+10,5.741000e+10
eps (basic),2.090000e+00,2.320000e+00,3.000000e+00,2.990000e+00,3.310000e+00
eps (basic) growth,NaN,1.102000e-01,2.956000e-01,-3.700000e-03,1.060000e-01
basic shares outstanding,2.188000e+10,2.087000e+10,1.982000e+10,1.847000e+10,1.735000e+10
eps (diluted),2.080000e+00,2.300000e+00,2.980000e+00,2.970000e+00,3.280000e+00
eps (diluted) growth,NaN,1.083000e-01,2.932000e-01,-2.000000e-03,1.023000e-01
diluted shares outstanding,5.251635e+08,2.101000e+10,-1.474836e+09,1.860000e+10,1.753000e+10
ebitda,6.828000e+10,6.943000e+10,8.034000e+10,7.454000e+10,7.640000e+10
ebitda growth,NaN,1.680000e-02,1.572000e-01,-7.220000e-02,2.490000e-02
ebitda margin,NaN,NaN,NaN,NaN,2.787000e-01

In [2]:
#%%timeit
import pandas as pd
import numpy as np
# import html5lib
# from bs4 import BeautifulSoup

def get_statement(ticker):
    balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
    income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
    cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
    urls = [balance_sheet_url, income_url, cashflow_url]
    tables_list = []  # list for all table dataframes
    pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
               'B': ' * 1000000000',  # convert B to ' * 1000000000'
               'M': ' * 1000000',     # convert M to ' * 1000000'
               'K': ' * 1000',        # convert K to ' * 1000'
               '%': ' / 100'          # convert % to ' / 100'
              }
    for url in urls:
        tables = pd.read_html(url, match="Item", index_col=0) # Scrape only tables with word 'Item' in it
        for i in range(len(tables)):
            # remove the duplicate from index.
            tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
            if not tables[i].columns[-1].isdigit(): # If a column has no digit character, drop it
                tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
            # 1. replace '-' with np.nan
            # 2. replace according regex patern dictionary
            # 3. evaluate the arithmetic symbols with pd.eval
            tables_list.append(tables[i].replace("-", np.nan).replace(pattern, regex=True).applymap(pd.eval, na_action='ignore'))
    return tables_list

def define_ebitda(tables_list):
    if 'ebitda' in tables_list[2].index:
        return tables_list[2].loc['ebitda']
    else:
        return tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense']
    
def get_financial_df(tables_list):
    tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index', inplace=True)
    return pd.DataFrame({'shareholderequity': tables_list[1].loc['total shareholders\' equity'],
              'longtermdebt': tables_list[1].loc['long-term debt'],
              'eps': tables_list[2].loc['eps (basic)'],
              'epsgrowth': tables_list[2].loc['eps (basic) growth'],
              'netincome': tables_list[2].loc['net income'],
              'roa': tables_list[1].loc['total shareholders\' equity / assets'],
              'interestexpense': tables_list[2].loc['total interest expense'],
              'ebitda': define_ebitda(tables_list)
             })
df = get_financial_df(get_statement('aapl'))
print(df)

      shareholderequity  longtermdebt   eps  epsgrowth     netincome     roa  \
2016       1.282500e+11  7.543000e+10  2.09        NaN  4.569000e+10  0.3987
2017       1.340500e+11  9.721000e+10  2.32     0.1102  4.835000e+10  0.3572
2018       1.071500e+11  9.374000e+10  3.00     0.2956  5.953000e+10  0.2930
2019       9.049000e+10  9.181000e+10  2.99    -0.0037  5.526000e+10  0.2673
2020       6.534000e+10  1.070500e+11  3.31     0.1060  5.741000e+10  0.2017

      interestexpense        ebitda
2016     1.460000e+09  6.828000e+10
2017     2.320000e+09  6.943000e+10
2018     3.240000e+09  8.034000e+10
2019     3.580000e+09  7.454000e+10
2020     2.870000e+09  7.640000e+10

In [3]:
df

,shareholderequity,longtermdebt,eps,epsgrowth,netincome,roa,interestexpense,ebitda
2016,1.282500e+11,7.543000e+10,2.09,NaN,4.569000e+10,0.3987,1.460000e+09,6.828000e+10
2017,1.340500e+11,9.721000e+10,2.32,0.1102,4.835000e+10,0.3572,2.320000e+09,6.943000e+10
2018,1.071500e+11,9.374000e+10,3.00,0.2956,5.953000e+10,0.2930,3.240000e+09,8.034000e+10
2019,9.049000e+10,9.181000e+10,2.99,-0.0037,5.526000e+10,0.2673,3.580000e+09,7.454000e+10
2020,6.534000e+10,1.070500e+11,3.31,0.1060,5.741000e+10,0.2017,2.870000e+09,7.640000e+10

In [8]:
df.epsgrowth.drop(df.index[0], axis='rows') > 0

2017     True
2018     True
2019    False
2020     True
Name: epsgrowth, dtype: bool

In [10]:
#
(df.epsgrowth.drop(df.index[0], axis='rows') > 0).all()

False

In [12]:
df['roe'] = df.netincome / df.shareholderequity

In [13]:
df

,shareholderequity,longtermdebt,eps,epsgrowth,netincome,roa,interestexpense,ebitda,roe
2016,1.282500e+11,7.543000e+10,2.09,NaN,4.569000e+10,0.3987,1.460000e+09,6.828000e+10,0.356257
2017,1.340500e+11,9.721000e+10,2.32,0.1102,4.835000e+10,0.3572,2.320000e+09,6.943000e+10,0.360686
2018,1.071500e+11,9.374000e+10,3.00,0.2956,5.953000e+10,0.2930,3.240000e+09,8.034000e+10,0.555576
2019,9.049000e+10,9.181000e+10,2.99,-0.0037,5.526000e+10,0.2673,3.580000e+09,7.454000e+10,0.610675
2020,6.534000e+10,1.070500e+11,3.31,0.1060,5.741000e+10,0.2017,2.870000e+09,7.640000e+10,0.878635

In [14]:
df['interestcoverageratio'] = df.ebitda / df.interestexpense

In [15]:
df

,shareholderequity,longtermdebt,eps,epsgrowth,netincome,roa,interestexpense,ebitda,roe,interestcoverageratio
2016,1.282500e+11,7.543000e+10,2.09,NaN,4.569000e+10,0.3987,1.460000e+09,6.828000e+10,0.356257,46.767123
2017,1.340500e+11,9.721000e+10,2.32,0.1102,4.835000e+10,0.3572,2.320000e+09,6.943000e+10,0.360686,29.926724
2018,1.071500e+11,9.374000e+10,3.00,0.2956,5.953000e+10,0.2930,3.240000e+09,8.034000e+10,0.555576,24.796296
2019,9.049000e+10,9.181000e+10,2.99,-0.0037,5.526000e+10,0.2673,3.580000e+09,7.454000e+10,0.610675,20.821229
2020,6.534000e+10,1.070500e+11,3.31,0.1060,5.741000e+10,0.2017,2.870000e+09,7.640000e+10,0.878635,26.620209

In [16]:
df.ebitda / df.longtermdebt

2016    0.905210
2017    0.714227
2018    0.857051
2019    0.811894
2020    0.713685
dtype: float64

In [21]:
import pandas as pd
import numpy as np
# import html5lib
# from bs4 import BeautifulSoup

def get_statement(ticker):
    balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
    income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
    cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
    urls = [balance_sheet_url, income_url, cashflow_url]
    tables_list = []  # list for all table dataframes
    pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
               'B': ' * 1000000000',  # convert B to ' * 1000000000'
               'M': ' * 1000000',     # convert M to ' * 1000000'
               'K': ' * 1000',        # convert K to ' * 1000'
               '%': ' / 100'          # convert % to ' / 100'
              }
    for url in urls:
        tables = pd.read_html(url, match="Item", index_col=0) # Scrape only tables with word 'Item' in it
        for i in range(len(tables)):
            # remove the duplicate from index.
            tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
            if not tables[i].columns[-1].isdigit(): # If a column has no digit character, drop it
                tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
            # 1. replace '-' with np.nan
            # 2. replace according regex patern dictionary
            # 3. evaluate the arithmetic symbols with pd.eval
            tables_list.append(tables[i].replace("-", np.nan).replace(pattern, regex=True).applymap(pd.eval, na_action='ignore'))
    return tables_list

def define_ebitda(tables_list):
    if 'ebitda' in tables_list[2].index:
        return tables_list[2].loc['ebitda']
    else:
        return tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense']
    
def get_financial_df(tables_list):
    tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index', inplace=True)
    return pd.DataFrame({'shareholderequity': tables_list[1].loc['total shareholders\' equity'],
              'longtermdebt': tables_list[1].loc['long-term debt'],
              'eps': tables_list[2].loc['eps (basic)'],
              'epsgrowth': tables_list[2].loc['eps (basic) growth'],
              'netincome': tables_list[2].loc['net income'],
              'roa': tables_list[1].loc['total shareholders\' equity / assets'],
              'interestexpense': tables_list[2].loc['total interest expense'],
              'ebitda': define_ebitda(tables_list)
             })
df = get_financial_df(get_statement('aapl'))
df['roe'] = df.netincome / df.shareholderequity
df['interestcoverageratio'] = df.ebitda / df.interestexpense
print(df)

      shareholderequity  longtermdebt   eps  epsgrowth     netincome     roa  \
2016       1.282500e+11  7.543000e+10  2.09        NaN  4.569000e+10  0.3987
2017       1.340500e+11  9.721000e+10  2.32     0.1102  4.835000e+10  0.3572
2018       1.071500e+11  9.374000e+10  3.00     0.2956  5.953000e+10  0.2930
2019       9.049000e+10  9.181000e+10  2.99    -0.0037  5.526000e+10  0.2673
2020       6.534000e+10  1.070500e+11  3.31     0.1060  5.741000e+10  0.2017

      interestexpense        ebitda       roe  interestcoverageratio
2016     1.460000e+09  6.828000e+10  0.356257              46.767123
2017     2.320000e+09  6.943000e+10  0.360686              29.926724
2018     3.240000e+09  8.034000e+10  0.555576              24.796296
2019     3.580000e+09  7.454000e+10  0.610675              20.821229
2020     2.870000e+09  7.640000e+10  0.878635              26.620209

In [22]:
df

,shareholderequity,longtermdebt,eps,epsgrowth,netincome,roa,interestexpense,ebitda,roe,interestcoverageratio
2016,1.282500e+11,7.543000e+10,2.09,NaN,4.569000e+10,0.3987,1.460000e+09,6.828000e+10,0.356257,46.767123
2017,1.340500e+11,9.721000e+10,2.32,0.1102,4.835000e+10,0.3572,2.320000e+09,6.943000e+10,0.360686,29.926724
2018,1.071500e+11,9.374000e+10,3.00,0.2956,5.953000e+10,0.2930,3.240000e+09,8.034000e+10,0.555576,24.796296
2019,9.049000e+10,9.181000e+10,2.99,-0.0037,5.526000e+10,0.2673,3.580000e+09,7.454000e+10,0.610675,20.821229
2020,6.534000e+10,1.070500e+11,3.31,0.1060,5.741000e+10,0.2017,2.870000e+09,7.640000e+10,0.878635,26.620209

In [28]:
df.index[df.eps > 2.5]
#df.epsgrowth.drop(df.index[0], axis='rows') > 0

Index(['2018', '2019', '2020'], dtype='object')

In [29]:
df.index[df.epsgrowth < 0]

Index(['2019'], dtype='object')

In [30]:
df.loc['2019', 'epsgrowth']

-0.0037

In [33]:
df.loc[df.index[df.eps > 2.5], 'eps']

2018    3.00
2019    2.99
2020    3.31
Name: eps, dtype: float64

In [40]:
index_list = df.index[df.eps > 2.5].tolist()
eps_list = df.eps[index_list].tolist()

In [66]:
for i in range(len(index_list)):
    print(index_list[i], eps_list[i])

2018 3.0
2019 2.99
2020 3.31

In [71]:
index_list = df.index[df.epsgrowth < 0].tolist()
epsgrowth_list = df.epsgrowth[index_list].tolist()

In [72]:
print(index_list, epsgrowth_list)

['2019'] [-0.0037]

In [73]:
df.roe

2016    0.356257
2017    0.360686
2018    0.555576
2019    0.610675
2020    0.878635
Name: roe, dtype: float64

In [74]:
df.roe.mean()

0.552365992368825

In [77]:
ratio = df.longtermdebt / df.netincome
ratio

2016    1.650908
2017    2.010548
2018    1.574668
2019    1.661419
2020    1.864658
dtype: float64

In [115]:
#
dfprice = pd.DataFrame(columns=['ticker', 'annualgrowthrate', 'lasteps', 'futureeps'])
pd.options.display.float_format = '{:20,.2f}'.format

In [109]:
import numpy_financial as npf

In [116]:
#
annualgrowthrate = npf.rate(5, 0, -1*df.eps.iloc[0], df.eps.iloc[-1])
annualgrowthrate

0.0963174872033299

In [117]:
print(df.eps.iloc[0], df.eps.iloc[-1])

2.09 3.31

In [118]:
2.09*(1+0.0963174872033299)**5

3.309999999999999

In [119]:
#
lasteps = df.eps[-1]
lasteps

3.31

In [120]:
#
n_year = 10
futureeps = abs(npf.fv(annualgrowthrate, n_year, 0, lasteps))
futureeps
ticker = 'aapl'

dfprice

           annualgrowthrate              lasteps            futureeps
ticker
aapl                   0.10                 3.31                 8.30

In [121]:
# get_stock_price
import datetime as dt
from pandas_datareader import data

today = dt.datetime.now()
def get_stock_price(ticker):
    stockprice_df = data.DataReader(name=ticker, data_source="yahoo", start=today -
                    dt.timedelta(days=5*365), end=today)
    return {'data': [{
        'x': stockprice_df.index,
        'y': stockprice_df.Close.values}]}

In [123]:
ticker = 'aapl'
raw_data = get_stock_price(ticker)

In [125]:
raw_data['data']

[{'x': DatetimeIndex(['2016-03-22', '2016-03-23', '2016-03-24', '2016-03-28',
                 '2016-03-29', '2016-03-30', '2016-03-31', '2016-04-01',
                 '2016-04-04', '2016-04-05',
                 ...
                 '2021-03-08', '2021-03-09', '2021-03-10', '2021-03-11',
                 '2021-03-12', '2021-03-15', '2021-03-16', '2021-03-17',
                 '2021-03-18', '2021-03-19'],
                dtype='datetime64[ns]', name='Date', length=1258, freq=None),
  'y': array([ 26.68000031,  26.53249931,  26.41749954, ..., 124.76000214,
         120.52999878, 119.98999786])}]

In [128]:
raw_data['data'][0]

{'x': DatetimeIndex(['2016-03-22', '2016-03-23', '2016-03-24', '2016-03-28',
                '2016-03-29', '2016-03-30', '2016-03-31', '2016-04-01',
                '2016-04-04', '2016-04-05',
                ...
                '2021-03-08', '2021-03-09', '2021-03-10', '2021-03-11',
                '2021-03-12', '2021-03-15', '2021-03-16', '2021-03-17',
                '2021-03-18', '2021-03-19'],
               dtype='datetime64[ns]', name='Date', length=1258, freq=None),
 'y': array([ 26.68000031,  26.53249931,  26.41749954, ..., 124.76000214,
        120.52999878, 119.98999786])}

In [129]:
raw_data['data'][0]['x'][:5]

DatetimeIndex(['2016-03-22', '2016-03-23', '2016-03-24', '2016-03-28',
               '2016-03-29'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [130]:
raw_data['data'][0]['y'][:5]

array([26.68000031, 26.53249931, 26.41749954, 26.29750061, 26.92000008])

In [3]:
# get stock price
import datetime as dt
from pandas_datareader import data

def get_stock_price(ticker):
    today = dt.datetime.now()
    stockprice_df = data.DataReader(name=ticker, data_source="yahoo", start=today -
                    dt.timedelta(days=5*365), end=today)
    return stockprice_df.Close

def format_stockprice_df(stockprice_df):
    return {'data': [{
        'x': stockprice_df.index,
        'y': stockprice_df.Close.values}]}

In [5]:
ticker = 'aapl'
stockprice_df = pd.DataFrame(get_stock_price(ticker))
stockprice_df['year'] = stockprice_df.index.year
stockprice_endyear = stockprice_df.groupby('year').tail(1).set_index('year')
stockprice_endyear

           Close
year
2016   28.955000
2017   42.307499
2018   39.435001
2019   73.412498
2020  132.690002
2021  119.989998

In [6]:
stockprice_df = pd.DataFrame(get_stock_price(ticker))
stockprice_df.head()

                Close
Date
2016-03-23  26.532499
2016-03-24  26.417500
2016-03-28  26.297501
2016-03-29  26.920000
2016-03-30  27.389999

In [8]:
stockprice_df['year'] = stockprice_df.index.year
stockprice_df.head()

                Close  year
Date
2016-03-23  26.532499  2016
2016-03-24  26.417500  2016
2016-03-28  26.297501  2016
2016-03-29  26.920000  2016
2016-03-30  27.389999  2016

In [146]:
list(stockprice_df.groupby('year'))
#stockpricedf.groupby('year').head(1).set_index('year')

[(2016,
                            Close  year
  Date
  2016-03-22                26.68  2016
  2016-03-23                26.53  2016
  2016-03-24                26.42  2016
  2016-03-28                26.30  2016
  2016-03-29                26.92  2016
  ...                         ...   ...
  2016-12-23                29.13  2016
  2016-12-27                29.32  2016
  2016-12-28                29.19  2016
  2016-12-29                29.18  2016
  2016-12-30                28.95  2016

  [198 rows x 2 columns]),
 (2017,
                            Close  year
  Date
  2017-01-03                29.04  2017
  2017-01-04                29.00  2017
  2017-01-05                29.15  2017
  2017-01-06                29.48  2017
  2017-01-09                29.75  2017
  ...                         ...   ...
  2017-12-22                43.75  2017
  2017-12-26                42.64  2017
  2017-12-27                42.65  2017
  2017-12-28                42.77  2017
  2017-12-29                42.31  2017

  [251 rows x 2 columns]),
 (2018,
                            Close  year
  Date
  2018-01-02                43.06  2018
  2018-01-03                43.06  2018
  2018-01-04                43.26  2018
  2018-01-05                43.75  2018
  2018-01-08                43.59  2018
  ...                         ...   ...
  2018-12-24                36.71  2018
  2018-12-26                39.29  2018
  2018-12-27                39.04  2018
  2018-12-28                39.06  2018
  2018-12-31                39.44  2018

  [251 rows x 2 columns]),
 (2019,
                            Close  year
  Date
  2019-01-02                39.48  2019
  2019-01-03                35.55  2019
  2019-01-04                37.06  2019
  2019-01-07                36.98  2019
  2019-01-08                37.69  2019
  ...                         ...   ...
  2019-12-24                71.07  2019
  2019-12-26                72.48  2019
  2019-12-27                72.45  2019
  2019-12-30                72.88  2019
  2019-12-31                73.41  2019

  [252 rows x 2 columns]),
 (2020,
                            Close  year
  Date
  2020-01-02                75.09  2020
  2020-01-03                74.36  2020
  2020-01-06                74.95  2020
  2020-01-07                74.60  2020
  2020-01-08                75.80  2020
  ...                         ...   ...
  2020-12-24               131.97  2020
  2020-12-28               136.69  2020
  2020-12-29               134.87  2020
  2020-12-30               133.72  2020
  2020-12-31               132.69  2020

  [253 rows x 2 columns]),
 (2021,
                            Close  year
  Date
  2021-01-04               129.41  2021
  2021-01-05               131.01  2021
  2021-01-06               126.60  2021
  2021-01-07               130.92  2021
  2021-01-08               132.05  2021
  2021-01-11               128.98  2021
  2021-01-12               128.80  2021
  2021-01-13               130.89  2021
  2021-01-14               128.91  2021
  2021-01-15               127.14  2021
  2021-01-19               127.83  2021
  2021-01-20               132.03  2021
  2021-01-21               136.87  2021
  2021-01-22               139.07  2021
  2021-01-25               142.92  2021
  2021-01-26               143.16  2021
  2021-01-27               142.06  2021
  2021-01-28               137.09  2021
  2021-01-29               131.96  2021
  2021-02-01               134.14  2021
  2021-02-02               134.99  2021
  2021-02-03               133.94  2021
  2021-02-04               137.39  2021
  2021-02-05               136.76  2021
  2021-02-08               136.91  2021
  2021-02-09               136.01  2021
  2021-02-10               135.39  2021
  2021-02-11               135.13  2021
  2021-02-12               135.37  2021
  2021-02-16               133.19  2021
  2021-02-17               130.84  2021
  2021-02-18               129.71  2021
  2021-02-19               129.87  2021
  2021-02-22               126.00  2021
  2021-02-23               125.86  2021
  2021-02-24               125.35  2021
  2021-02-25               120.99  2021
  2021-02-26               121.26  2021
  2021-03-01               127.79  2021
  2021-03-02               125.12  2021
  2021-03-03               122.06  2021
  2021-03-04               120.13  2021
  2021-03-05               121.42  2021
  2021-03-08               116.36  2021
  2021-03-09               121.09  2021
  2021-03-10               119.98  2021
  2021-03-11               121.96  2021
  2021-03-12               121.03  2021
  2021-03-15               123.99  2021
  2021-03-16               125.57  2021
  2021-03-17               124.76  2021
  2021-03-18               120.53  2021
  2021-03-19               119.99  2021)]

In [154]:
stockprice_df.groupby('year').tail(3)#.set_index('year')

                          Close  year
Date
2016-12-28                29.19  2016
2016-12-29                29.18  2016
2016-12-30                28.95  2016
2017-12-27                42.65  2017
2017-12-28                42.77  2017
2017-12-29                42.31  2017
2018-12-27                39.04  2018
2018-12-28                39.06  2018
2018-12-31                39.44  2018
2019-12-27                72.45  2019
2019-12-30                72.88  2019
2019-12-31                73.41  2019
2020-12-29               134.87  2020
2020-12-30               133.72  2020
2020-12-31               132.69  2020
2021-03-17               124.76  2021
2021-03-18               120.53  2021
2021-03-19               119.99  2021

In [9]:
stockprice_df.groupby('year').tail(1).set_index('year')

           Close
year
2016   28.955000
2017   42.307499
2018   39.435001
2019   73.412498
2020  132.690002
2021  119.989998

In [163]:
priceearning_byyear = pd.DataFrame()
print(stockprice_df.groupby('year').tail(1).set_index('year'))
print(type(stockprice_df.groupby('year').tail(1).set_index('year')))
priceearning_byyear['price'] = stockprice_df.groupby('year').tail(1).set_index('year')['Close']
#priceearning_byyear['eps'] = financialdf['eps']
#priceearning_byyear['pe'] = priceearning_byyear['price']/priceearning_byyear['eps']
priceearning_byyear

                    Close
year
2016                28.95
2017                42.31
2018                39.44
2019                73.41
2020               132.69
2021               119.99
<class 'pandas.core.frame.DataFrame'>

                    price
year
2016                28.95
2017                42.31
2018                39.44
2019                73.41
2020               132.69
2021               119.99

In [159]:
stockprice_df

                          Close  year
Date
2016-03-22                26.68  2016
2016-03-23                26.53  2016
2016-03-24                26.42  2016
2016-03-28                26.30  2016
2016-03-29                26.92  2016
...                         ...   ...
2021-03-15               123.99  2021
2021-03-16               125.57  2021
2021-03-17               124.76  2021
2021-03-18               120.53  2021
2021-03-19               119.99  2021

[1258 rows x 2 columns]

In [1]:
import pandas as pd
import numpy as np
def get_statement(ticker):
    balance_sheet_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/balance-sheet"
    income_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials"
    #cashflow_url = "https://www.marketwatch.com/investing/stock/" + ticker + "/financials/cash-flow"
    #urls = [balance_sheet_url, income_url, cashflow_url]
    urls = [balance_sheet_url, income_url]
    tables_list = []  # list for all table dataframes
    pattern = {'\((.*)\)': '-\\1',    # convert (x) to -x
               'B': ' * 1000000000',  # convert B to ' * 1000000000'
               'M': ' * 1000000',     # convert M to ' * 1000000'
               'K': ' * 1000',        # convert K to ' * 1000'
               '%': ' / 100'          # convert % to ' / 100'
              }
    for url in urls:
        tables = pd.read_html(url, match="Item", index_col=0) # Scrape only tables with word 'Item' in it
        for i in range(len(tables)):
            # remove the duplicate from index.
            tables[i].index = list(map(lambda x: " ".join(dict.fromkeys(x.lower().split())), tables[i].index))
            if not tables[i].columns[-1].isdigit(): # If a column has no digit character, drop it
                tables[i].drop(tables[i].columns[-1], axis="columns", inplace=True)
            # 1. replace '-' with np.nan
            # 2. replace according regex patern dictionary
            # 3. evaluate the arithmetic symbols with pd.eval
            tables_list.append(tables[i].replace("-", np.nan).replace(pattern, regex=True).applymap(pd.eval, na_action='ignore'))
    return tables_list
def define_ebitda(tables_list):
    if 'ebitda' in tables_list[2].index:
        return tables_list[2].loc['ebitda']
    else:
        return tables_list[2].loc['net income'].values - tables_list[2].loc['total interest expense'].values - tables_list[2].loc['income tax'].values - tables_list[2].loc['depreciation & amortization expense']
    
def get_financial_df(tables_list):
    tables_list[2].rename({'interest expense': 'total interest expense',
                      'income taxes': 'income tax'}, axis='index', inplace=True)
    return pd.DataFrame({'shareholderequity': tables_list[1].loc['total shareholders\' equity'],
              'longtermdebt': tables_list[1].loc['long-term debt'],
              'eps': tables_list[2].loc['eps (basic)'],
              'epsgrowth': tables_list[2].loc['eps (basic) growth'],
              'netincome': tables_list[2].loc['net income'],
              'roa': tables_list[1].loc['total shareholders\' equity / assets'],
              'interestexpense': tables_list[2].loc['total interest expense'],
              'ebitda': define_ebitda(tables_list)
             })

def calculate_ratio(financial_df):
    financial_df['roe'] = financial_df.netincome / financial_df.shareholderequity
    financial_df['interestcoverageratio'] = financial_df.ebitda / financial_df.interestexpense
    return financial_df

In [15]:
stockprice_df['year'] = stockprice_df.index.year
priceearning_byyear = pd.DataFrame()
financialdf = calculate_ratio(get_financial_df(get_statement(ticker)))
financialdf.index.rename('year', inplace=True)
priceearning_byyear['eps'] = financialdf['eps']
print(type(priceearning_byyear))
priceearning_byyear

<class 'pandas.core.frame.DataFrame'>

       eps
year
2016  2.09
2017  2.32
2018  3.00
2019  2.99
2020  3.31

In [44]:
#print(priceearning_byyear)
#print(type(priceearning_byyear))
price = stockprice_df.groupby('year').tail(1).set_index('year')['Close']
print(type(price))
price

<class 'pandas.core.series.Series'>

year
2016     28.955000
2017     42.307499
2018     39.435001
2019     73.412498
2020    132.690002
2021    119.989998
Name: Close, dtype: float64

In [30]:
priceearning_byyear.merge(price.to_frame(name='price'), how='left', left_on='year', right_index=True)

       eps       price
year
2016  2.09   28.955000
2017  2.32   42.307499
2018  3.00   39.435001
2019  2.99   73.412498
2020  3.31  132.690002

In [20]:
type(price.index[0])

numpy.int64

In [21]:
priceearning_byyear.index

Index(['2016', '2017', '2018', '2019', '2020'], dtype='object', name='year')

In [27]:
priceearning_byyear.index = priceearning_byyear.index.astype(int)

In [28]:
priceearning_byyear.index

Int64Index([2016, 2017, 2018, 2019, 2020], dtype='int64', name='year')

In [38]:
priceearning_byyear = priceearning_byyear.merge(price.to_frame(name='price'), left_index=True, right_index=True)

In [39]:
priceearning_byyear

       eps       price
year
2016  2.09   28.955000
2017  2.32   42.307499
2018  3.00   39.435001
2019  2.99   73.412498
2020  3.31  132.690002

In [40]:
priceearning_byyear['peratio'] = priceearning_byyear.price/priceearning_byyear.eps

In [41]:
priceearning_byyear

       eps       price    peratio
year
2016  2.09   28.955000  13.854067
2017  2.32   42.307499  18.235991
2018  3.00   39.435001  13.145000
2019  2.99   73.412498  24.552675
2020  3.31  132.690002  40.087614

In [42]:
stockprice_df

                 Close  year
Date
2016-03-23   26.532499  2016
2016-03-24   26.417500  2016
2016-03-28   26.297501  2016
2016-03-29   26.920000  2016
2016-03-30   27.389999  2016
...                ...   ...
2021-03-15  123.989998  2021
2021-03-16  125.570000  2021
2021-03-17  124.760002  2021
2021-03-18  120.529999  2021
2021-03-19  119.989998  2021

[1257 rows x 2 columns]

In [1]:
import pandas as pd
import xlwings as xw

In [2]:
df = pd.read_html("https://stockmarketmba.com/nonuscompaniesonusexchanges.php")

In [5]:
df

[    Symbol                                  Name Index Country  \
 0     ABCL              AbCellera Biologics Inc.        Canada
 1     ABUS         Arbutus Biopharma Corporation        Canada
 2     ACIU                          AC Immune SA   Switzerland
 3     ADCT                   ADC Therapeutics SA   Switzerland
 4     AEHL  Antelope Enterprise Holdings Limited         China
 ..     ...                                   ...           ...
 290    YVR               Liquid Media Group Ltd.        Canada
 291   ZCMD              Zhongchao Inc. - Class A         China
 292   ZKIN       Zk International Group Co., Ltd         China
 293   ZYME                        Zymeworks Inc.        Canada
 294  TOTAL                                   294           NaN

     Country of incorporation             GICS Sector Foreign issuer?  \
 0                        NaN             Health Care              No
 1                     Canada             Health Care              No
 2                Switzerland             Health Care             Yes
 3                        NaN             Health Care             Yes
 4                        NaN               Materials             Yes
 ..                       ...                     ...             ...
 290                      NaN  Consumer Discretionary             Yes
 291                      NaN             Health Care             Yes
 292                      NaN               Materials             Yes
 293                   Canada             Health Care              No
 294                      NaN                     NaN             NaN

         Russell 3000?      Market cap  Average Volume   Action
 0                  No  $6,582,314,376        950675.0  Analyze
 1                  No    $321,161,954       1920054.0  Analyze
 2                  No    $548,877,311        325215.0  Analyze
 3                  No  $1,926,477,945        471991.0  Analyze
 4                  No      $9,759,183       1637762.0  Analyze
 ..                ...             ...             ...      ...
 290                No     $41,275,605      21676729.0  Analyze
 291                No     $40,577,009       7398548.0  Analyze
 292                No    $208,949,289      10102842.0  Analyze
 293                No  $1,486,944,083        395913.0  Analyze
 294  $796,852,309,224             NaN             NaN      NaN

 [295 rows x 10 columns]]

In [3]:
xw.view(df)

TypeError: Objects for SAFEARRAYS must be sequences (of sequences), or a buffer object.

In [7]:
links = ["https://stockmarketmba.com/nonuscompaniesonusexchanges.php", "https://stockmarketmba.com/listofadrs.php"]

In [21]:
def last_column(symbol, name):
    requirements = [symbol.lower()=="total", name.isdigit()]
    return all(requirements)

In [30]:
df_list = []
links = ["https://stockmarketmba.com/nonuscompaniesonusexchanges.php",
          "https://stockmarketmba.com/listofadrs.php"]
for i in links:
    df = pd.read_html(i)[0][['Symbol', 'Name', 'GICS Sector']]
    if last_column(df.iloc[-1]['Symbol'], df.iloc[-1]['Name']):
        df_list.append(df.iloc[:-1])
    else:
        df_list.append(df)
df = pd.concat(df_list).reset_index(drop=True)
xw.view(df)

In [29]:
df.iloc[-1]

Symbol         TOTAL
Name             294
GICS Sector      NaN
Name: 294, dtype: object

In [17]:
type(df_list[0])

pandas.core.frame.DataFrame

In [18]:
df = pd.concat(df_list)

In [20]:
xw.view(df.reset_index(drop=True))

In [1]:
import math

millnames = ['',' Thousand',' Million',' Billion',' Trillion']

def millify(n):
    n = float(n)
    millidx = max(0,min(len(millnames)-1,
                        int(math.floor(0 if n == 0 else math.log10(abs(n))/3))))

    return '{:.0f}{}'.format(n / 10**(3 * millidx), millnames[millidx])

In [7]:
numlist = ['0', '100', '750', '1001', '1555', '1999', '231345', '12312454346456']
result = map(millify, numlist)
list(result)

['0',
 '100',
 '750',
 '1 Thousand',
 '2 Thousand',
 '2 Thousand',
 '231 Thousand',
 '12 Trillion']

In [9]:
import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)

if __name__ == '__main__':
    app.run_server()

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

In [13]:
df = pd.DataFrame({'state':['Ohio', 'Nevada'],
             'pop':[2, 6],
             'year':[2000, 2001]})
df

    state  pop  year
0    Ohio    2  2000
1  Nevada    6  2001

In [14]:
df.to_dict()

{'state': {0: 'Ohio', 1: 'Nevada'},
 'pop': {0: 2, 1: 6},
 'year': {0: 2000, 1: 2001}}

In [15]:
a_dict = {'state': {},
 'pop': {},
 'year': {}}

In [16]:
a_dict

{'state': {}, 'pop': {}, 'year': {}}

In [17]:
import xlwings as xw
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')
xw.view(df)

In [19]:
df.to_dict('records')

[{'State': 'California',
  'Number of Solar Plants': 289,
  'Installed Capacity (MW)': 4395,
  'Average MW Per Plant': 15.3,
  'Generation (GWh)': 10826},
 {'State': 'Arizona',
  'Number of Solar Plants': 48,
  'Installed Capacity (MW)': 1078,
  'Average MW Per Plant': 22.5,
  'Generation (GWh)': 2550},
 {'State': 'Nevada',
  'Number of Solar Plants': 11,
  'Installed Capacity (MW)': 238,
  'Average MW Per Plant': 21.6,
  'Generation (GWh)': 557},
 {'State': 'New Mexico',
  'Number of Solar Plants': 33,
  'Installed Capacity (MW)': 261,
  'Average MW Per Plant': 7.9,
  'Generation (GWh)': 590},
 {'State': 'Colorado',
  'Number of Solar Plants': 20,
  'Installed Capacity (MW)': 118,
  'Average MW Per Plant': 5.9,
  'Generation (GWh)': 235},
 {'State': 'Texas',
  'Number of Solar Plants': 12,
  'Installed Capacity (MW)': 187,
  'Average MW Per Plant': 15.6,
  'Generation (GWh)': 354},
 {'State': 'North Carolina',
  'Number of Solar Plants': 148,
  'Installed Capacity (MW)': 669,
  'Average MW Per Plant': 4.5,
  'Generation (GWh)': 1162},
 {'State': 'New York',
  'Number of Solar Plants': 13,
  'Installed Capacity (MW)': 53,
  'Average MW Per Plant': 4.1,
  'Generation (GWh)': 84}]

In [20]:
df.to_dict()

{'State': {0: 'California',
  1: 'Arizona',
  2: 'Nevada',
  3: 'New Mexico',
  4: 'Colorado',
  5: 'Texas',
  6: 'North Carolina',
  7: 'New York'},
 'Number of Solar Plants': {0: 289,
  1: 48,
  2: 11,
  3: 33,
  4: 20,
  5: 12,
  6: 148,
  7: 13},
 'Installed Capacity (MW)': {0: 4395,
  1: 1078,
  2: 238,
  3: 261,
  4: 118,
  5: 187,
  6: 669,
  7: 53},
 'Average MW Per Plant': {0: 15.3,
  1: 22.5,
  2: 21.6,
  3: 7.9,
  4: 5.9,
  5: 15.6,
  6: 4.5,
  7: 4.1},
 'Generation (GWh)': {0: 10826,
  1: 2550,
  2: 557,
  3: 590,
  4: 235,
  5: 354,
  6: 1162,
  7: 84}}

In [12]:
remove_coma = lambda x : x.replace(',', '') if type(x) == str else pass

SyntaxError: invalid syntax (<ipython-input-12-6e285f78f11a>, line 1)

In [7]:
test = lambda x : True if (x > 10 and x < 20) else False

In [1]:
a = '123,456'

True